/* Generated by Yosys 0.9 (git sha1 1979e0b1, i686-w64-mingw32.static-g++ 5.5.0 -Os) */

(* top =  1  *)
(* src = "arbitro_estruct.v:1" *)
module arbitro_estruct(clk, almost_full0, almost_full1, almost_full2, almost_full3, state, empty0_naranja, empty1_naranja, empty2_naranja, empty3_naranja, empty0_morado, empty1_morado, empty2_morado, empty3_morado, push0, push1, push2, push3, pop0, pop1, pop2, pop3, empties);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  (* src = "arbitro_estruct.v:3" *)
  input almost_full0;
  (* src = "arbitro_estruct.v:4" *)
  input almost_full1;
  (* src = "arbitro_estruct.v:5" *)
  input almost_full2;
  (* src = "arbitro_estruct.v:6" *)
  input almost_full3;
  (* src = "arbitro_estruct.v:2" *)
  input clk;
  (* src = "arbitro_estruct.v:24" *)
  output [7:0] empties;
  (* src = "arbitro_estruct.v:12" *)
  input empty0_morado;
  (* src = "arbitro_estruct.v:8" *)
  input empty0_naranja;
  (* src = "arbitro_estruct.v:13" *)
  input empty1_morado;
  (* src = "arbitro_estruct.v:9" *)
  input empty1_naranja;
  (* src = "arbitro_estruct.v:14" *)
  input empty2_morado;
  (* src = "arbitro_estruct.v:10" *)
  input empty2_naranja;
  (* src = "arbitro_estruct.v:15" *)
  input empty3_morado;
  (* src = "arbitro_estruct.v:11" *)
  input empty3_naranja;
  (* src = "arbitro_estruct.v:20" *)
  output pop0;
  (* src = "arbitro_estruct.v:21" *)
  output pop1;
  (* src = "arbitro_estruct.v:22" *)
  output pop2;
  (* src = "arbitro_estruct.v:23" *)
  output pop3;
  (* src = "arbitro_estruct.v:16" *)
  output push0;
  (* src = "arbitro_estruct.v:17" *)
  output push1;
  (* src = "arbitro_estruct.v:18" *)
  output push2;
  (* src = "arbitro_estruct.v:19" *)
  output push3;
  (* src = "arbitro_estruct.v:7" *)
  input [3:0] state;
  NOT _22_ (
    .A(state[3]),
    .Y(_00_)
  );
  NOT _23_ (
    .A(empty3_morado),
    .Y(_01_)
  );
  NOT _24_ (
    .A(empty2_morado),
    .Y(_02_)
  );
  NOT _25_ (
    .A(empty1_morado),
    .Y(_03_)
  );
  NOT _26_ (
    .A(empty2_naranja),
    .Y(_04_)
  );
  NOT _27_ (
    .A(empty0_morado),
    .Y(_05_)
  );
  NOT _28_ (
    .A(empty3_naranja),
    .Y(_06_)
  );
  NOT _29_ (
    .A(state[0]),
    .Y(_07_)
  );
  NOR _30_ (
    .A(state[1]),
    .B(state[2]),
    .Y(_08_)
  );
  NOT _31_ (
    .A(_08_),
    .Y(_09_)
  );
  NOR _32_ (
    .A(state[3]),
    .B(_07_),
    .Y(_10_)
  );
  NAND _33_ (
    .A(_00_),
    .B(state[0]),
    .Y(_11_)
  );
  NOR _34_ (
    .A(_09_),
    .B(_11_),
    .Y(_12_)
  );
  NAND _35_ (
    .A(_08_),
    .B(_10_),
    .Y(_13_)
  );
  NOR _36_ (
    .A(_01_),
    .B(_12_),
    .Y(empties[7])
  );
  NOR _37_ (
    .A(_02_),
    .B(_12_),
    .Y(empties[6])
  );
  NOR _38_ (
    .A(_03_),
    .B(_12_),
    .Y(empties[5])
  );
  NOR _39_ (
    .A(_04_),
    .B(_12_),
    .Y(empties[2])
  );
  NOR _40_ (
    .A(_05_),
    .B(_12_),
    .Y(empties[4])
  );
  NOR _41_ (
    .A(_06_),
    .B(_12_),
    .Y(empties[3])
  );
  NAND _42_ (
    .A(empty1_naranja),
    .B(_13_),
    .Y(_14_)
  );
  NOT _43_ (
    .A(_14_),
    .Y(empties[1])
  );
  NAND _44_ (
    .A(empty0_naranja),
    .B(_13_),
    .Y(_15_)
  );
  NOT _45_ (
    .A(_15_),
    .Y(empties[0])
  );
  NOR _46_ (
    .A(_04_),
    .B(empty3_naranja),
    .Y(_16_)
  );
  NAND _47_ (
    .A(empty0_naranja),
    .B(_16_),
    .Y(_17_)
  );
  NOR _48_ (
    .A(_14_),
    .B(_17_),
    .Y(pop3)
  );
  NAND _49_ (
    .A(_04_),
    .B(empty0_naranja),
    .Y(_18_)
  );
  NOR _50_ (
    .A(_14_),
    .B(_18_),
    .Y(pop2)
  );
  NOR _51_ (
    .A(empty1_naranja),
    .B(_15_),
    .Y(pop1)
  );
  NOR _52_ (
    .A(empty0_naranja),
    .B(_12_),
    .Y(pop0)
  );
  NOR _53_ (
    .A(almost_full0),
    .B(almost_full1),
    .Y(_19_)
  );
  NOR _54_ (
    .A(almost_full2),
    .B(almost_full3),
    .Y(_20_)
  );
  NAND _55_ (
    .A(_19_),
    .B(_20_),
    .Y(_21_)
  );
  NOT _56_ (
    .A(_21_),
    .Y(push0)
  );
  assign push1 = push0;
  assign push2 = push0;
  assign push3 = push0;
endmodule
