/* Generated by Yosys 0.9+4052 (git sha1 44520808, gcc 9.3.0-17ubuntu1~20.04 -fPIC -Os) */

(* top =  1  *)
(* src = "arbitro_estruct.v:1.1-133.10" *)
module arbitro_estruct(clk, almost_full0, almost_full1, almost_full2, almost_full3, state, empty0_naranja, empty1_naranja, empty2_naranja, empty3_naranja, empty0_morado, empty1_morado, empty2_morado, empty3_morado, push, pop0, pop1, pop2, pop3, empties);
  (* src = "arbitro_estruct.v:27.1-35.4" *)
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  (* src = "arbitro_estruct.v:3.11-3.23" *)
  input almost_full0;
  (* src = "arbitro_estruct.v:4.11-4.23" *)
  input almost_full1;
  (* src = "arbitro_estruct.v:5.11-5.23" *)
  input almost_full2;
  (* src = "arbitro_estruct.v:6.11-6.23" *)
  input almost_full3;
  (* src = "arbitro_estruct.v:2.11-2.14" *)
  input clk;
  (* src = "arbitro_estruct.v:24.22-24.29" *)
  output [7:0] empties;
  (* src = "arbitro_estruct.v:12.11-12.24" *)
  input empty0_morado;
  (* src = "arbitro_estruct.v:8.11-8.25" *)
  input empty0_naranja;
  (* src = "arbitro_estruct.v:13.11-13.24" *)
  input empty1_morado;
  (* src = "arbitro_estruct.v:9.11-9.25" *)
  input empty1_naranja;
  (* src = "arbitro_estruct.v:14.11-14.24" *)
  input empty2_morado;
  (* src = "arbitro_estruct.v:10.11-10.25" *)
  input empty2_naranja;
  (* src = "arbitro_estruct.v:15.11-15.24" *)
  input empty3_morado;
  (* src = "arbitro_estruct.v:11.11-11.25" *)
  input empty3_naranja;
  (* src = "arbitro_estruct.v:20.16-20.20" *)
  output pop0;
  (* src = "arbitro_estruct.v:21.16-21.20" *)
  output pop1;
  (* src = "arbitro_estruct.v:22.16-22.20" *)
  output pop2;
  (* src = "arbitro_estruct.v:23.16-23.20" *)
  output pop3;
  (* src = "arbitro_estruct.v:16.16-16.20" *)
  output push;
  (* src = "arbitro_estruct.v:7.17-7.22" *)
  input [3:0] state;
  NOT _24_ (
    .A(state[3]),
    .Y(_01_)
  );
  NOT _25_ (
    .A(empty3_morado),
    .Y(_02_)
  );
  NOT _26_ (
    .A(empty2_morado),
    .Y(_03_)
  );
  NOT _27_ (
    .A(empty1_morado),
    .Y(_04_)
  );
  NOT _28_ (
    .A(empty0_morado),
    .Y(_05_)
  );
  NOT _29_ (
    .A(empty3_naranja),
    .Y(_06_)
  );
  NOT _30_ (
    .A(empty2_naranja),
    .Y(_07_)
  );
  NOT _31_ (
    .A(empty1_naranja),
    .Y(_08_)
  );
  NOT _32_ (
    .A(empty0_naranja),
    .Y(_09_)
  );
  NOR _33_ (
    .A(state[1]),
    .B(state[2]),
    .Y(_10_)
  );
  NOT _34_ (
    .A(_10_),
    .Y(_11_)
  );
  NAND _35_ (
    .A(_01_),
    .B(state[0]),
    .Y(_12_)
  );
  NOR _36_ (
    .A(_11_),
    .B(_12_),
    .Y(_13_)
  );
  NOT _37_ (
    .A(_13_),
    .Y(_00_)
  );
  NOR _38_ (
    .A(_02_),
    .B(_13_),
    .Y(empties[7])
  );
  NOR _39_ (
    .A(_03_),
    .B(_13_),
    .Y(empties[6])
  );
  NOR _40_ (
    .A(_04_),
    .B(_13_),
    .Y(empties[5])
  );
  NOR _41_ (
    .A(_05_),
    .B(_13_),
    .Y(empties[4])
  );
  NOR _42_ (
    .A(_06_),
    .B(_13_),
    .Y(empties[3])
  );
  NOR _43_ (
    .A(_07_),
    .B(_13_),
    .Y(empties[2])
  );
  NOR _44_ (
    .A(_08_),
    .B(_13_),
    .Y(empties[1])
  );
  NOR _45_ (
    .A(_09_),
    .B(_13_),
    .Y(empties[0])
  );
  NAND _46_ (
    .A(empty1_naranja),
    .B(empties[0]),
    .Y(_14_)
  );
  NOR _47_ (
    .A(almost_full0),
    .B(almost_full1),
    .Y(_15_)
  );
  NOR _48_ (
    .A(almost_full2),
    .B(almost_full3),
    .Y(_16_)
  );
  NAND _49_ (
    .A(_15_),
    .B(_16_),
    .Y(_17_)
  );
  NOR _50_ (
    .A(_07_),
    .B(_17_),
    .Y(_18_)
  );
  NAND _51_ (
    .A(_06_),
    .B(_18_),
    .Y(_19_)
  );
  NOR _52_ (
    .A(_14_),
    .B(_19_),
    .Y(pop3)
  );
  NOR _53_ (
    .A(empty2_naranja),
    .B(_17_),
    .Y(_20_)
  );
  NOT _54_ (
    .A(_20_),
    .Y(_21_)
  );
  NOR _55_ (
    .A(_14_),
    .B(_21_),
    .Y(pop2)
  );
  NAND _56_ (
    .A(_08_),
    .B(empties[0]),
    .Y(_22_)
  );
  NOR _57_ (
    .A(_17_),
    .B(_22_),
    .Y(pop1)
  );
  NAND _58_ (
    .A(_09_),
    .B(_00_),
    .Y(_23_)
  );
  NOR _59_ (
    .A(_17_),
    .B(_23_),
    .Y(pop0)
  );
  (* src = "arbitro_estruct.v:27.1-35.4" *)
  DFF _60_ (
    .C(clk),
    .D(_00_),
    .Q(push)
  );
endmodule
