/* Generated by Yosys 0.9+4052 (git sha1 44520808, gcc 9.3.0-17ubuntu1~20.04 -fPIC -Os) */

(* top =  1  *)
(* src = "Contador_estruct.v:1.1-74.10" *)
module Contador_estruct(data_FIFO_0, data_FIFO_1, data_FIFO_2, data_FIFO_3, req, clk, state, idx, valid, data_out);
  (* src = "Contador_estruct.v:43.1-72.4" *)
  wire [4:0] _000_;
  (* src = "Contador_estruct.v:43.1-72.4" *)
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  (* src = "Contador_estruct.v:7.11-7.14" *)
  input clk;
  (* src = "Contador_estruct.v:14.11-14.21" *)
  wire [4:0] contador_0;
  (* src = "Contador_estruct.v:14.23-14.33" *)
  wire [4:0] contador_1;
  (* src = "Contador_estruct.v:14.35-14.45" *)
  wire [4:0] contador_2;
  (* src = "Contador_estruct.v:14.47-14.57" *)
  wire [4:0] contador_3;
  (* src = "Contador_estruct.v:2.17-2.28" *)
  input [9:0] data_FIFO_0;
  (* src = "Contador_estruct.v:3.17-3.28" *)
  input [9:0] data_FIFO_1;
  (* src = "Contador_estruct.v:4.17-4.28" *)
  input [9:0] data_FIFO_2;
  (* src = "Contador_estruct.v:5.17-5.28" *)
  input [9:0] data_FIFO_3;
  (* src = "Contador_estruct.v:11.22-11.30" *)
  output [4:0] data_out;
  reg [4:0] data_out;
  (* src = "Contador_estruct.v:9.17-9.20" *)
  input [1:0] idx;
  (* src = "Contador_estruct.v:6.11-6.14" *)
  input req;
  (* src = "Contador_estruct.v:8.17-8.22" *)
  input [3:0] state;
  (* src = "Contador_estruct.v:10.16-10.21" *)
  output valid;
  reg valid;
  NOT _185_ (
    .A(contador_3[4]),
    .Y(_182_)
  );
  NOT _186_ (
    .A(contador_3[3]),
    .Y(_183_)
  );
  NOT _187_ (
    .A(contador_3[1]),
    .Y(_184_)
  );
  NOT _188_ (
    .A(contador_2[3]),
    .Y(_023_)
  );
  NOT _189_ (
    .A(contador_2[1]),
    .Y(_024_)
  );
  NOT _190_ (
    .A(contador_1[4]),
    .Y(_025_)
  );
  NOT _191_ (
    .A(contador_1[3]),
    .Y(_026_)
  );
  NOT _192_ (
    .A(contador_1[2]),
    .Y(_027_)
  );
  NOT _193_ (
    .A(contador_1[1]),
    .Y(_028_)
  );
  NOT _194_ (
    .A(contador_1[0]),
    .Y(_029_)
  );
  NOT _195_ (
    .A(contador_0[3]),
    .Y(_030_)
  );
  NOT _196_ (
    .A(contador_0[1]),
    .Y(_031_)
  );
  NOT _197_ (
    .A(idx[1]),
    .Y(_032_)
  );
  NOT _198_ (
    .A(state[0]),
    .Y(_033_)
  );
  NOR _199_ (
    .A(data_FIFO_3[6]),
    .B(data_FIFO_3[7]),
    .Y(_034_)
  );
  NOR _200_ (
    .A(data_FIFO_3[8]),
    .B(data_FIFO_3[9]),
    .Y(_035_)
  );
  NAND _201_ (
    .A(_034_),
    .B(_035_),
    .Y(_036_)
  );
  NOR _202_ (
    .A(data_FIFO_3[0]),
    .B(data_FIFO_3[1]),
    .Y(_037_)
  );
  NOR _203_ (
    .A(data_FIFO_3[3]),
    .B(data_FIFO_3[4]),
    .Y(_038_)
  );
  NOR _204_ (
    .A(data_FIFO_3[2]),
    .B(data_FIFO_3[5]),
    .Y(_039_)
  );
  NAND _205_ (
    .A(_037_),
    .B(_039_),
    .Y(_040_)
  );
  NOR _206_ (
    .A(_036_),
    .B(_040_),
    .Y(_041_)
  );
  NAND _207_ (
    .A(_038_),
    .B(_041_),
    .Y(_042_)
  );
  NAND _208_ (
    .A(contador_3[0]),
    .B(_042_),
    .Y(_043_)
  );
  NOR _209_ (
    .A(_184_),
    .B(_043_),
    .Y(_044_)
  );
  NAND _210_ (
    .A(contador_3[2]),
    .B(_044_),
    .Y(_045_)
  );
  NOT _211_ (
    .A(_045_),
    .Y(_046_)
  );
  NAND _212_ (
    .A(contador_3[3]),
    .B(_046_),
    .Y(_047_)
  );
  NOR _213_ (
    .A(state[1]),
    .B(state[3]),
    .Y(_048_)
  );
  NOR _214_ (
    .A(state[2]),
    .B(_033_),
    .Y(_049_)
  );
  NAND _215_ (
    .A(_048_),
    .B(_049_),
    .Y(_050_)
  );
  NOT _216_ (
    .A(_050_),
    .Y(_051_)
  );
  NAND _217_ (
    .A(_183_),
    .B(_045_),
    .Y(_052_)
  );
  NAND _218_ (
    .A(_047_),
    .B(_052_),
    .Y(_053_)
  );
  NOR _219_ (
    .A(_051_),
    .B(_053_),
    .Y(_021_)
  );
  NOR _220_ (
    .A(contador_3[2]),
    .B(_044_),
    .Y(_054_)
  );
  NAND _221_ (
    .A(_045_),
    .B(_050_),
    .Y(_055_)
  );
  NOR _222_ (
    .A(_054_),
    .B(_055_),
    .Y(_020_)
  );
  NAND _223_ (
    .A(_184_),
    .B(_043_),
    .Y(_056_)
  );
  NAND _224_ (
    .A(_050_),
    .B(_056_),
    .Y(_057_)
  );
  NOR _225_ (
    .A(_044_),
    .B(_057_),
    .Y(_019_)
  );
  NOR _226_ (
    .A(contador_3[0]),
    .B(_042_),
    .Y(_058_)
  );
  NAND _227_ (
    .A(_043_),
    .B(_050_),
    .Y(_059_)
  );
  NOR _228_ (
    .A(_058_),
    .B(_059_),
    .Y(_018_)
  );
  NOR _229_ (
    .A(data_FIFO_2[6]),
    .B(data_FIFO_2[7]),
    .Y(_060_)
  );
  NOR _230_ (
    .A(data_FIFO_2[8]),
    .B(data_FIFO_2[9]),
    .Y(_061_)
  );
  NAND _231_ (
    .A(_060_),
    .B(_061_),
    .Y(_062_)
  );
  NOR _232_ (
    .A(data_FIFO_2[0]),
    .B(data_FIFO_2[1]),
    .Y(_063_)
  );
  NOR _233_ (
    .A(data_FIFO_2[3]),
    .B(data_FIFO_2[4]),
    .Y(_064_)
  );
  NOR _234_ (
    .A(data_FIFO_2[2]),
    .B(data_FIFO_2[5]),
    .Y(_065_)
  );
  NAND _235_ (
    .A(_063_),
    .B(_065_),
    .Y(_066_)
  );
  NOR _236_ (
    .A(_062_),
    .B(_066_),
    .Y(_067_)
  );
  NAND _237_ (
    .A(_064_),
    .B(_067_),
    .Y(_068_)
  );
  NAND _238_ (
    .A(contador_2[0]),
    .B(_068_),
    .Y(_069_)
  );
  NOR _239_ (
    .A(_024_),
    .B(_069_),
    .Y(_070_)
  );
  NAND _240_ (
    .A(contador_2[2]),
    .B(_070_),
    .Y(_071_)
  );
  NOR _241_ (
    .A(_023_),
    .B(_071_),
    .Y(_072_)
  );
  NOR _242_ (
    .A(contador_2[4]),
    .B(_072_),
    .Y(_073_)
  );
  NAND _243_ (
    .A(contador_2[4]),
    .B(_072_),
    .Y(_074_)
  );
  NAND _244_ (
    .A(_050_),
    .B(_074_),
    .Y(_075_)
  );
  NOR _245_ (
    .A(_073_),
    .B(_075_),
    .Y(_017_)
  );
  NAND _246_ (
    .A(_023_),
    .B(_071_),
    .Y(_076_)
  );
  NAND _247_ (
    .A(_050_),
    .B(_076_),
    .Y(_077_)
  );
  NOR _248_ (
    .A(_072_),
    .B(_077_),
    .Y(_016_)
  );
  NOR _249_ (
    .A(contador_2[2]),
    .B(_070_),
    .Y(_078_)
  );
  NAND _250_ (
    .A(_050_),
    .B(_071_),
    .Y(_079_)
  );
  NOR _251_ (
    .A(_078_),
    .B(_079_),
    .Y(_015_)
  );
  NAND _252_ (
    .A(_024_),
    .B(_069_),
    .Y(_080_)
  );
  NAND _253_ (
    .A(_050_),
    .B(_080_),
    .Y(_081_)
  );
  NOR _254_ (
    .A(_070_),
    .B(_081_),
    .Y(_014_)
  );
  NOR _255_ (
    .A(contador_2[0]),
    .B(_068_),
    .Y(_082_)
  );
  NAND _256_ (
    .A(_050_),
    .B(_069_),
    .Y(_083_)
  );
  NOR _257_ (
    .A(_082_),
    .B(_083_),
    .Y(_013_)
  );
  NOR _258_ (
    .A(data_FIFO_1[6]),
    .B(data_FIFO_1[7]),
    .Y(_084_)
  );
  NOR _259_ (
    .A(data_FIFO_1[8]),
    .B(data_FIFO_1[9]),
    .Y(_085_)
  );
  NAND _260_ (
    .A(_084_),
    .B(_085_),
    .Y(_086_)
  );
  NOR _261_ (
    .A(data_FIFO_1[0]),
    .B(data_FIFO_1[1]),
    .Y(_087_)
  );
  NOR _262_ (
    .A(data_FIFO_1[3]),
    .B(data_FIFO_1[4]),
    .Y(_088_)
  );
  NOR _263_ (
    .A(data_FIFO_1[2]),
    .B(data_FIFO_1[5]),
    .Y(_089_)
  );
  NAND _264_ (
    .A(_087_),
    .B(_089_),
    .Y(_090_)
  );
  NOR _265_ (
    .A(_086_),
    .B(_090_),
    .Y(_091_)
  );
  NAND _266_ (
    .A(_088_),
    .B(_091_),
    .Y(_092_)
  );
  NAND _267_ (
    .A(contador_1[0]),
    .B(_092_),
    .Y(_093_)
  );
  NOR _268_ (
    .A(_028_),
    .B(_093_),
    .Y(_094_)
  );
  NAND _269_ (
    .A(contador_1[2]),
    .B(_094_),
    .Y(_095_)
  );
  NOR _270_ (
    .A(_026_),
    .B(_095_),
    .Y(_096_)
  );
  NOR _271_ (
    .A(contador_1[4]),
    .B(_096_),
    .Y(_097_)
  );
  NAND _272_ (
    .A(contador_1[4]),
    .B(_096_),
    .Y(_098_)
  );
  NAND _273_ (
    .A(_050_),
    .B(_098_),
    .Y(_099_)
  );
  NOR _274_ (
    .A(_097_),
    .B(_099_),
    .Y(_012_)
  );
  NAND _275_ (
    .A(_026_),
    .B(_095_),
    .Y(_100_)
  );
  NAND _276_ (
    .A(_050_),
    .B(_100_),
    .Y(_101_)
  );
  NOR _277_ (
    .A(_096_),
    .B(_101_),
    .Y(_011_)
  );
  NOR _278_ (
    .A(contador_1[2]),
    .B(_094_),
    .Y(_102_)
  );
  NAND _279_ (
    .A(_050_),
    .B(_095_),
    .Y(_103_)
  );
  NOR _280_ (
    .A(_102_),
    .B(_103_),
    .Y(_010_)
  );
  NAND _281_ (
    .A(_028_),
    .B(_093_),
    .Y(_104_)
  );
  NAND _282_ (
    .A(_050_),
    .B(_104_),
    .Y(_105_)
  );
  NOR _283_ (
    .A(_094_),
    .B(_105_),
    .Y(_009_)
  );
  NOR _284_ (
    .A(contador_1[0]),
    .B(_092_),
    .Y(_106_)
  );
  NAND _285_ (
    .A(_050_),
    .B(_093_),
    .Y(_107_)
  );
  NOR _286_ (
    .A(_106_),
    .B(_107_),
    .Y(_008_)
  );
  NOR _287_ (
    .A(data_FIFO_0[6]),
    .B(data_FIFO_0[7]),
    .Y(_108_)
  );
  NOR _288_ (
    .A(data_FIFO_0[8]),
    .B(data_FIFO_0[9]),
    .Y(_109_)
  );
  NAND _289_ (
    .A(_108_),
    .B(_109_),
    .Y(_110_)
  );
  NOR _290_ (
    .A(data_FIFO_0[0]),
    .B(data_FIFO_0[1]),
    .Y(_111_)
  );
  NOR _291_ (
    .A(data_FIFO_0[3]),
    .B(data_FIFO_0[4]),
    .Y(_112_)
  );
  NOR _292_ (
    .A(data_FIFO_0[2]),
    .B(data_FIFO_0[5]),
    .Y(_113_)
  );
  NAND _293_ (
    .A(_111_),
    .B(_113_),
    .Y(_114_)
  );
  NOR _294_ (
    .A(_110_),
    .B(_114_),
    .Y(_115_)
  );
  NAND _295_ (
    .A(_112_),
    .B(_115_),
    .Y(_116_)
  );
  NAND _296_ (
    .A(contador_0[0]),
    .B(_116_),
    .Y(_117_)
  );
  NOR _297_ (
    .A(_031_),
    .B(_117_),
    .Y(_118_)
  );
  NAND _298_ (
    .A(contador_0[2]),
    .B(_118_),
    .Y(_119_)
  );
  NOR _299_ (
    .A(_030_),
    .B(_119_),
    .Y(_120_)
  );
  NOR _300_ (
    .A(contador_0[4]),
    .B(_120_),
    .Y(_121_)
  );
  NAND _301_ (
    .A(contador_0[4]),
    .B(_120_),
    .Y(_122_)
  );
  NAND _302_ (
    .A(_050_),
    .B(_122_),
    .Y(_123_)
  );
  NOR _303_ (
    .A(_121_),
    .B(_123_),
    .Y(_007_)
  );
  NAND _304_ (
    .A(_030_),
    .B(_119_),
    .Y(_124_)
  );
  NAND _305_ (
    .A(_050_),
    .B(_124_),
    .Y(_125_)
  );
  NOR _306_ (
    .A(_120_),
    .B(_125_),
    .Y(_006_)
  );
  NOR _307_ (
    .A(contador_0[2]),
    .B(_118_),
    .Y(_126_)
  );
  NAND _308_ (
    .A(_050_),
    .B(_119_),
    .Y(_127_)
  );
  NOR _309_ (
    .A(_126_),
    .B(_127_),
    .Y(_005_)
  );
  NAND _310_ (
    .A(_031_),
    .B(_117_),
    .Y(_128_)
  );
  NAND _311_ (
    .A(_050_),
    .B(_128_),
    .Y(_129_)
  );
  NOR _312_ (
    .A(_118_),
    .B(_129_),
    .Y(_004_)
  );
  NOR _313_ (
    .A(contador_0[0]),
    .B(_116_),
    .Y(_130_)
  );
  NAND _314_ (
    .A(_050_),
    .B(_117_),
    .Y(_131_)
  );
  NOR _315_ (
    .A(_130_),
    .B(_131_),
    .Y(_003_)
  );
  NAND _316_ (
    .A(state[2]),
    .B(req),
    .Y(_132_)
  );
  NAND _317_ (
    .A(_033_),
    .B(_048_),
    .Y(_133_)
  );
  NOR _318_ (
    .A(_132_),
    .B(_133_),
    .Y(_001_)
  );
  NOR _319_ (
    .A(idx[0]),
    .B(_032_),
    .Y(_134_)
  );
  NAND _320_ (
    .A(idx[0]),
    .B(_032_),
    .Y(_135_)
  );
  NOT _321_ (
    .A(_135_),
    .Y(_136_)
  );
  NOR _322_ (
    .A(_134_),
    .B(_136_),
    .Y(_137_)
  );
  NAND _323_ (
    .A(contador_0[0]),
    .B(_137_),
    .Y(_138_)
  );
  NOR _324_ (
    .A(_029_),
    .B(_135_),
    .Y(_139_)
  );
  NOR _325_ (
    .A(contador_2[0]),
    .B(idx[0]),
    .Y(_140_)
  );
  NAND _326_ (
    .A(idx[0]),
    .B(idx[1]),
    .Y(_141_)
  );
  NOR _327_ (
    .A(_032_),
    .B(_140_),
    .Y(_142_)
  );
  NOR _328_ (
    .A(_139_),
    .B(_142_),
    .Y(_143_)
  );
  NAND _329_ (
    .A(_138_),
    .B(_143_),
    .Y(_144_)
  );
  NOR _330_ (
    .A(contador_3[0]),
    .B(_141_),
    .Y(_145_)
  );
  NAND _331_ (
    .A(_050_),
    .B(_144_),
    .Y(_146_)
  );
  NOR _332_ (
    .A(_145_),
    .B(_146_),
    .Y(_000_[0])
  );
  NAND _333_ (
    .A(contador_0[1]),
    .B(_137_),
    .Y(_147_)
  );
  NOR _334_ (
    .A(_028_),
    .B(_135_),
    .Y(_148_)
  );
  NOR _335_ (
    .A(contador_2[1]),
    .B(idx[0]),
    .Y(_149_)
  );
  NOR _336_ (
    .A(_032_),
    .B(_149_),
    .Y(_150_)
  );
  NOR _337_ (
    .A(_148_),
    .B(_150_),
    .Y(_151_)
  );
  NAND _338_ (
    .A(_147_),
    .B(_151_),
    .Y(_152_)
  );
  NOR _339_ (
    .A(contador_3[1]),
    .B(_141_),
    .Y(_153_)
  );
  NAND _340_ (
    .A(_050_),
    .B(_152_),
    .Y(_154_)
  );
  NOR _341_ (
    .A(_153_),
    .B(_154_),
    .Y(_000_[1])
  );
  NAND _342_ (
    .A(contador_0[2]),
    .B(_137_),
    .Y(_155_)
  );
  NOR _343_ (
    .A(_027_),
    .B(_135_),
    .Y(_156_)
  );
  NOR _344_ (
    .A(contador_2[2]),
    .B(idx[0]),
    .Y(_157_)
  );
  NOR _345_ (
    .A(_032_),
    .B(_157_),
    .Y(_158_)
  );
  NOR _346_ (
    .A(_156_),
    .B(_158_),
    .Y(_159_)
  );
  NAND _347_ (
    .A(_155_),
    .B(_159_),
    .Y(_160_)
  );
  NOR _348_ (
    .A(contador_3[2]),
    .B(_141_),
    .Y(_161_)
  );
  NAND _349_ (
    .A(_050_),
    .B(_160_),
    .Y(_162_)
  );
  NOR _350_ (
    .A(_161_),
    .B(_162_),
    .Y(_000_[2])
  );
  NAND _351_ (
    .A(contador_0[3]),
    .B(_137_),
    .Y(_163_)
  );
  NOR _352_ (
    .A(_026_),
    .B(_135_),
    .Y(_164_)
  );
  NOR _353_ (
    .A(contador_2[3]),
    .B(idx[0]),
    .Y(_165_)
  );
  NOR _354_ (
    .A(_032_),
    .B(_165_),
    .Y(_166_)
  );
  NOR _355_ (
    .A(_164_),
    .B(_166_),
    .Y(_167_)
  );
  NAND _356_ (
    .A(_163_),
    .B(_167_),
    .Y(_168_)
  );
  NOR _357_ (
    .A(contador_3[3]),
    .B(_141_),
    .Y(_169_)
  );
  NAND _358_ (
    .A(_050_),
    .B(_168_),
    .Y(_170_)
  );
  NOR _359_ (
    .A(_169_),
    .B(_170_),
    .Y(_000_[3])
  );
  NAND _360_ (
    .A(contador_0[4]),
    .B(_137_),
    .Y(_171_)
  );
  NOR _361_ (
    .A(_025_),
    .B(_135_),
    .Y(_172_)
  );
  NOR _362_ (
    .A(contador_2[4]),
    .B(idx[0]),
    .Y(_173_)
  );
  NOR _363_ (
    .A(_032_),
    .B(_173_),
    .Y(_174_)
  );
  NOR _364_ (
    .A(_172_),
    .B(_174_),
    .Y(_175_)
  );
  NAND _365_ (
    .A(_171_),
    .B(_175_),
    .Y(_176_)
  );
  NOR _366_ (
    .A(contador_3[4]),
    .B(_141_),
    .Y(_177_)
  );
  NAND _367_ (
    .A(_050_),
    .B(_176_),
    .Y(_178_)
  );
  NOR _368_ (
    .A(_177_),
    .B(_178_),
    .Y(_000_[4])
  );
  NOR _369_ (
    .A(_182_),
    .B(_047_),
    .Y(_179_)
  );
  NAND _370_ (
    .A(_182_),
    .B(_047_),
    .Y(_180_)
  );
  NAND _371_ (
    .A(_050_),
    .B(_180_),
    .Y(_181_)
  );
  NOR _372_ (
    .A(_179_),
    .B(_181_),
    .Y(_022_)
  );
  NOR _373_ (
    .A(_051_),
    .B(_001_),
    .Y(_002_)
  );
  (* src = "Contador_estruct.v:17.1-40.4" *)
  DFF _374_ (
    .C(clk),
    .D(_003_),
    .Q(contador_0[0])
  );
  (* src = "Contador_estruct.v:17.1-40.4" *)
  DFF _375_ (
    .C(clk),
    .D(_004_),
    .Q(contador_0[1])
  );
  (* src = "Contador_estruct.v:17.1-40.4" *)
  DFF _376_ (
    .C(clk),
    .D(_005_),
    .Q(contador_0[2])
  );
  (* src = "Contador_estruct.v:17.1-40.4" *)
  DFF _377_ (
    .C(clk),
    .D(_006_),
    .Q(contador_0[3])
  );
  (* src = "Contador_estruct.v:17.1-40.4" *)
  DFF _378_ (
    .C(clk),
    .D(_007_),
    .Q(contador_0[4])
  );
  (* src = "Contador_estruct.v:17.1-40.4" *)
  DFF _379_ (
    .C(clk),
    .D(_008_),
    .Q(contador_1[0])
  );
  (* src = "Contador_estruct.v:17.1-40.4" *)
  DFF _380_ (
    .C(clk),
    .D(_009_),
    .Q(contador_1[1])
  );
  (* src = "Contador_estruct.v:17.1-40.4" *)
  DFF _381_ (
    .C(clk),
    .D(_010_),
    .Q(contador_1[2])
  );
  (* src = "Contador_estruct.v:17.1-40.4" *)
  DFF _382_ (
    .C(clk),
    .D(_011_),
    .Q(contador_1[3])
  );
  (* src = "Contador_estruct.v:17.1-40.4" *)
  DFF _383_ (
    .C(clk),
    .D(_012_),
    .Q(contador_1[4])
  );
  (* src = "Contador_estruct.v:17.1-40.4" *)
  DFF _384_ (
    .C(clk),
    .D(_013_),
    .Q(contador_2[0])
  );
  (* src = "Contador_estruct.v:17.1-40.4" *)
  DFF _385_ (
    .C(clk),
    .D(_014_),
    .Q(contador_2[1])
  );
  (* src = "Contador_estruct.v:17.1-40.4" *)
  DFF _386_ (
    .C(clk),
    .D(_015_),
    .Q(contador_2[2])
  );
  (* src = "Contador_estruct.v:17.1-40.4" *)
  DFF _387_ (
    .C(clk),
    .D(_016_),
    .Q(contador_2[3])
  );
  (* src = "Contador_estruct.v:17.1-40.4" *)
  DFF _388_ (
    .C(clk),
    .D(_017_),
    .Q(contador_2[4])
  );
  (* src = "Contador_estruct.v:17.1-40.4" *)
  DFF _389_ (
    .C(clk),
    .D(_018_),
    .Q(contador_3[0])
  );
  (* src = "Contador_estruct.v:17.1-40.4" *)
  DFF _390_ (
    .C(clk),
    .D(_019_),
    .Q(contador_3[1])
  );
  (* src = "Contador_estruct.v:17.1-40.4" *)
  DFF _391_ (
    .C(clk),
    .D(_020_),
    .Q(contador_3[2])
  );
  (* src = "Contador_estruct.v:17.1-40.4" *)
  DFF _392_ (
    .C(clk),
    .D(_021_),
    .Q(contador_3[3])
  );
  (* src = "Contador_estruct.v:17.1-40.4" *)
  DFF _393_ (
    .C(clk),
    .D(_022_),
    .Q(contador_3[4])
  );
  (* src = "Contador_estruct.v:43.1-72.4" *)
  always @*
    if (!1'h0) valid = _001_;
  (* src = "Contador_estruct.v:43.1-72.4" *)
  always @*
    if (!_002_) data_out[0] = _000_[0];
  (* src = "Contador_estruct.v:43.1-72.4" *)
  always @*
    if (!_002_) data_out[1] = _000_[1];
  (* src = "Contador_estruct.v:43.1-72.4" *)
  always @*
    if (!_002_) data_out[2] = _000_[2];
  (* src = "Contador_estruct.v:43.1-72.4" *)
  always @*
    if (!_002_) data_out[3] = _000_[3];
  (* src = "Contador_estruct.v:43.1-72.4" *)
  always @*
    if (!_002_) data_out[4] = _000_[4];
endmodule
