/* Generated by Yosys 0.9+4052 (git sha1 44520808, gcc 9.3.0-17ubuntu1~20.04 -fPIC -Os) */

(* top =  1  *)
(* src = "FIFO_estruct.v:3.1-117.10" *)
module FIFO_estruct(clk, state, push, pop, data_in, umbral_superior, umbral_inferior, data_out, almost_full, almost_empty);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  (* src = "FIFO_estruct.v:12.29-12.41" *)
  output almost_empty;
  (* src = "FIFO_estruct.v:12.16-12.27" *)
  output almost_full;
  (* src = "FIFO_estruct.v:4.11-4.14" *)
  input clk;
  (* src = "FIFO_estruct.v:18.11-18.19" *)
  wire [2:0] contador;
  (* src = "FIFO_estruct.v:8.17-8.24" *)
  input [9:0] data_in;
  (* src = "FIFO_estruct.v:11.18-11.26" *)
  output [9:0] data_out;
  (* src = "FIFO_estruct.v:19.11-19.16" *)
  wire empty;
  (* src = "FIFO_estruct.v:19.5-19.9" *)
  wire full;
  (* src = "FIFO_estruct.v:16.11-16.20" *)
  reg [2:0] low_space;
  (* src = "FIFO_estruct.v:16.22-16.32" *)
  reg [2:0] much_space;
  (* src = "FIFO_estruct.v:7.11-7.14" *)
  input pop;
  (* src = "FIFO_estruct.v:6.11-6.15" *)
  input push;
  (* src = "FIFO_estruct.v:15.19-15.25" *)
  wire [2:0] rd_ptr;
  (* src = "FIFO_estruct.v:17.11-17.15" *)
  wire re_a;
  (* src = "FIFO_estruct.v:5.11-5.16" *)
  input state;
  (* src = "FIFO_estruct.v:10.17-10.32" *)
  input [2:0] umbral_inferior;
  (* src = "FIFO_estruct.v:9.17-9.32" *)
  input [2:0] umbral_superior;
  (* src = "FIFO_estruct.v:17.5-17.9" *)
  wire we_a;
  (* src = "FIFO_estruct.v:15.11-15.17" *)
  wire [2:0] wr_ptr;
  NOT _107_ (
    .A(rd_ptr[2]),
    .Y(_049_)
  );
  NOT _108_ (
    .A(rd_ptr[1]),
    .Y(_050_)
  );
  NOT _109_ (
    .A(rd_ptr[0]),
    .Y(_051_)
  );
  NOT _110_ (
    .A(wr_ptr[1]),
    .Y(_052_)
  );
  NOT _111_ (
    .A(contador[2]),
    .Y(_053_)
  );
  NOT _112_ (
    .A(contador[1]),
    .Y(_054_)
  );
  NOT _113_ (
    .A(contador[0]),
    .Y(_055_)
  );
  NOT _114_ (
    .A(full),
    .Y(_056_)
  );
  NOT _115_ (
    .A(empty),
    .Y(_057_)
  );
  NOT _116_ (
    .A(low_space[2]),
    .Y(_058_)
  );
  NOT _117_ (
    .A(much_space[2]),
    .Y(_059_)
  );
  NOT _118_ (
    .A(push),
    .Y(_060_)
  );
  NOT _119_ (
    .A(pop),
    .Y(_061_)
  );
  NOR _120_ (
    .A(empty),
    .B(_061_),
    .Y(_062_)
  );
  NAND _121_ (
    .A(_057_),
    .B(pop),
    .Y(_063_)
  );
  NOR _122_ (
    .A(_051_),
    .B(_063_),
    .Y(_064_)
  );
  NAND _123_ (
    .A(rd_ptr[0]),
    .B(_062_),
    .Y(_065_)
  );
  NOR _124_ (
    .A(_050_),
    .B(_065_),
    .Y(_066_)
  );
  NAND _125_ (
    .A(rd_ptr[1]),
    .B(_064_),
    .Y(_067_)
  );
  NAND _126_ (
    .A(_050_),
    .B(_065_),
    .Y(_068_)
  );
  NAND _127_ (
    .A(state),
    .B(_068_),
    .Y(_069_)
  );
  NOR _128_ (
    .A(_066_),
    .B(_069_),
    .Y(_009_)
  );
  NAND _129_ (
    .A(_051_),
    .B(_063_),
    .Y(_070_)
  );
  NAND _130_ (
    .A(state),
    .B(_070_),
    .Y(_071_)
  );
  NOR _131_ (
    .A(_064_),
    .B(_071_),
    .Y(_008_)
  );
  NOR _132_ (
    .A(full),
    .B(_060_),
    .Y(_072_)
  );
  NAND _133_ (
    .A(_056_),
    .B(push),
    .Y(_073_)
  );
  NAND _134_ (
    .A(wr_ptr[0]),
    .B(_072_),
    .Y(_074_)
  );
  NOR _135_ (
    .A(_052_),
    .B(_074_),
    .Y(_075_)
  );
  NOR _136_ (
    .A(wr_ptr[2]),
    .B(_075_),
    .Y(_076_)
  );
  NAND _137_ (
    .A(wr_ptr[2]),
    .B(_075_),
    .Y(_077_)
  );
  NAND _138_ (
    .A(state),
    .B(_077_),
    .Y(_078_)
  );
  NOR _139_ (
    .A(_076_),
    .B(_078_),
    .Y(_007_)
  );
  NAND _140_ (
    .A(_052_),
    .B(_074_),
    .Y(_079_)
  );
  NAND _141_ (
    .A(state),
    .B(_079_),
    .Y(_080_)
  );
  NOR _142_ (
    .A(_075_),
    .B(_080_),
    .Y(_006_)
  );
  NOR _143_ (
    .A(wr_ptr[0]),
    .B(_072_),
    .Y(_081_)
  );
  NAND _144_ (
    .A(state),
    .B(_074_),
    .Y(_082_)
  );
  NOR _145_ (
    .A(_081_),
    .B(_082_),
    .Y(_005_)
  );
  NOR _146_ (
    .A(contador[1]),
    .B(_055_),
    .Y(_083_)
  );
  NOR _147_ (
    .A(contador[1]),
    .B(contador[0]),
    .Y(_084_)
  );
  NOT _148_ (
    .A(_084_),
    .Y(_085_)
  );
  NAND _149_ (
    .A(_062_),
    .B(_084_),
    .Y(_086_)
  );
  NAND _150_ (
    .A(contador[2]),
    .B(_086_),
    .Y(_087_)
  );
  NAND _151_ (
    .A(contador[1]),
    .B(contador[0]),
    .Y(_088_)
  );
  NOT _152_ (
    .A(_088_),
    .Y(_089_)
  );
  NOR _153_ (
    .A(_062_),
    .B(_088_),
    .Y(_090_)
  );
  NAND _154_ (
    .A(_072_),
    .B(_090_),
    .Y(_091_)
  );
  NAND _155_ (
    .A(_087_),
    .B(_091_),
    .Y(_092_)
  );
  NAND _156_ (
    .A(state),
    .B(_092_),
    .Y(_093_)
  );
  NOT _157_ (
    .A(_093_),
    .Y(_004_)
  );
  NOR _158_ (
    .A(_054_),
    .B(contador[0]),
    .Y(_094_)
  );
  NOR _159_ (
    .A(_083_),
    .B(_094_),
    .Y(_095_)
  );
  NAND _160_ (
    .A(_062_),
    .B(_095_),
    .Y(_096_)
  );
  NOR _161_ (
    .A(contador[2]),
    .B(_085_),
    .Y(_097_)
  );
  NOT _162_ (
    .A(_097_),
    .Y(_098_)
  );
  NAND _163_ (
    .A(state),
    .B(_098_),
    .Y(_099_)
  );
  NOR _164_ (
    .A(_096_),
    .B(_097_),
    .Y(_100_)
  );
  NAND _165_ (
    .A(state),
    .B(_100_),
    .Y(_101_)
  );
  NOR _166_ (
    .A(_053_),
    .B(_088_),
    .Y(_102_)
  );
  NAND _167_ (
    .A(contador[2]),
    .B(_089_),
    .Y(_103_)
  );
  NOR _168_ (
    .A(_073_),
    .B(_102_),
    .Y(_104_)
  );
  NAND _169_ (
    .A(_072_),
    .B(_103_),
    .Y(_105_)
  );
  NAND _170_ (
    .A(_095_),
    .B(_104_),
    .Y(_106_)
  );
  NAND _171_ (
    .A(state),
    .B(_063_),
    .Y(_011_)
  );
  NOR _172_ (
    .A(contador[1]),
    .B(_072_),
    .Y(_012_)
  );
  NOR _173_ (
    .A(_011_),
    .B(_012_),
    .Y(_013_)
  );
  NAND _174_ (
    .A(_106_),
    .B(_013_),
    .Y(_014_)
  );
  NAND _175_ (
    .A(_101_),
    .B(_014_),
    .Y(_003_)
  );
  NAND _176_ (
    .A(_062_),
    .B(_097_),
    .Y(_015_)
  );
  NOR _177_ (
    .A(_062_),
    .B(_072_),
    .Y(_016_)
  );
  NAND _178_ (
    .A(state),
    .B(_055_),
    .Y(_017_)
  );
  NOR _179_ (
    .A(_016_),
    .B(_017_),
    .Y(_018_)
  );
  NAND _180_ (
    .A(_015_),
    .B(_018_),
    .Y(_019_)
  );
  NOR _181_ (
    .A(_055_),
    .B(_011_),
    .Y(_020_)
  );
  NAND _182_ (
    .A(_105_),
    .B(_020_),
    .Y(_021_)
  );
  NAND _183_ (
    .A(_019_),
    .B(_021_),
    .Y(_002_)
  );
  NOR _184_ (
    .A(_060_),
    .B(_103_),
    .Y(_022_)
  );
  NOR _185_ (
    .A(full),
    .B(_022_),
    .Y(_023_)
  );
  NOR _186_ (
    .A(_011_),
    .B(_023_),
    .Y(_001_)
  );
  NAND _187_ (
    .A(empty),
    .B(_073_),
    .Y(_024_)
  );
  NAND _188_ (
    .A(_015_),
    .B(_024_),
    .Y(_025_)
  );
  NAND _189_ (
    .A(state),
    .B(_025_),
    .Y(_026_)
  );
  NOT _190_ (
    .A(_026_),
    .Y(_000_)
  );
  NOR _191_ (
    .A(_054_),
    .B(much_space[1]),
    .Y(_027_)
  );
  NOR _192_ (
    .A(_055_),
    .B(much_space[0]),
    .Y(_028_)
  );
  NOR _193_ (
    .A(_027_),
    .B(_028_),
    .Y(_029_)
  );
  NAND _194_ (
    .A(_053_),
    .B(much_space[2]),
    .Y(_030_)
  );
  NAND _195_ (
    .A(_054_),
    .B(much_space[1]),
    .Y(_031_)
  );
  NAND _196_ (
    .A(_030_),
    .B(_031_),
    .Y(_032_)
  );
  NOR _197_ (
    .A(_029_),
    .B(_032_),
    .Y(_033_)
  );
  NAND _198_ (
    .A(contador[2]),
    .B(_059_),
    .Y(_034_)
  );
  NAND _199_ (
    .A(state),
    .B(_034_),
    .Y(_035_)
  );
  NOR _200_ (
    .A(_033_),
    .B(_035_),
    .Y(almost_empty)
  );
  NAND _201_ (
    .A(_054_),
    .B(low_space[1]),
    .Y(_036_)
  );
  NAND _202_ (
    .A(_055_),
    .B(low_space[0]),
    .Y(_037_)
  );
  NAND _203_ (
    .A(_036_),
    .B(_037_),
    .Y(_038_)
  );
  NOR _204_ (
    .A(_053_),
    .B(low_space[2]),
    .Y(_039_)
  );
  NOR _205_ (
    .A(_054_),
    .B(low_space[1]),
    .Y(_040_)
  );
  NOR _206_ (
    .A(_039_),
    .B(_040_),
    .Y(_041_)
  );
  NAND _207_ (
    .A(_038_),
    .B(_041_),
    .Y(_042_)
  );
  NOR _208_ (
    .A(contador[2]),
    .B(_058_),
    .Y(_043_)
  );
  NAND _209_ (
    .A(state),
    .B(_042_),
    .Y(_044_)
  );
  NOR _210_ (
    .A(_043_),
    .B(_044_),
    .Y(almost_full)
  );
  NOR _211_ (
    .A(_061_),
    .B(_099_),
    .Y(re_a)
  );
  NAND _212_ (
    .A(state),
    .B(push),
    .Y(_045_)
  );
  NOR _213_ (
    .A(_102_),
    .B(_045_),
    .Y(we_a)
  );
  NOR _214_ (
    .A(_049_),
    .B(_067_),
    .Y(_046_)
  );
  NAND _215_ (
    .A(_049_),
    .B(_067_),
    .Y(_047_)
  );
  NAND _216_ (
    .A(state),
    .B(_047_),
    .Y(_048_)
  );
  NOR _217_ (
    .A(_046_),
    .B(_048_),
    .Y(_010_)
  );
  (* src = "FIFO_estruct.v:32.1-65.4" *)
  DFF _218_ (
    .C(clk),
    .D(_000_),
    .Q(empty)
  );
  (* src = "FIFO_estruct.v:32.1-65.4" *)
  DFF _219_ (
    .C(clk),
    .D(_001_),
    .Q(full)
  );
  (* src = "FIFO_estruct.v:32.1-65.4" *)
  DFF _220_ (
    .C(clk),
    .D(_002_),
    .Q(contador[0])
  );
  (* src = "FIFO_estruct.v:32.1-65.4" *)
  DFF _221_ (
    .C(clk),
    .D(_003_),
    .Q(contador[1])
  );
  (* src = "FIFO_estruct.v:32.1-65.4" *)
  DFF _222_ (
    .C(clk),
    .D(_004_),
    .Q(contador[2])
  );
  (* src = "FIFO_estruct.v:32.1-65.4" *)
  DFF _223_ (
    .C(clk),
    .D(_005_),
    .Q(wr_ptr[0])
  );
  (* src = "FIFO_estruct.v:32.1-65.4" *)
  DFF _224_ (
    .C(clk),
    .D(_006_),
    .Q(wr_ptr[1])
  );
  (* src = "FIFO_estruct.v:32.1-65.4" *)
  DFF _225_ (
    .C(clk),
    .D(_007_),
    .Q(wr_ptr[2])
  );
  (* src = "FIFO_estruct.v:32.1-65.4" *)
  DFF _226_ (
    .C(clk),
    .D(_008_),
    .Q(rd_ptr[0])
  );
  (* src = "FIFO_estruct.v:32.1-65.4" *)
  DFF _227_ (
    .C(clk),
    .D(_009_),
    .Q(rd_ptr[1])
  );
  (* src = "FIFO_estruct.v:32.1-65.4" *)
  DFF _228_ (
    .C(clk),
    .D(_010_),
    .Q(rd_ptr[2])
  );
  (* src = "FIFO_estruct.v:92.1-115.4" *)
  always @*
    if (!state) low_space[0] = umbral_superior[0];
  (* src = "FIFO_estruct.v:92.1-115.4" *)
  always @*
    if (!state) low_space[1] = umbral_superior[1];
  (* src = "FIFO_estruct.v:92.1-115.4" *)
  always @*
    if (!state) low_space[2] = umbral_superior[2];
  (* src = "FIFO_estruct.v:92.1-115.4" *)
  always @*
    if (!state) much_space[0] = umbral_inferior[0];
  (* src = "FIFO_estruct.v:92.1-115.4" *)
  always @*
    if (!state) much_space[1] = umbral_inferior[1];
  (* src = "FIFO_estruct.v:92.1-115.4" *)
  always @*
    if (!state) much_space[2] = umbral_inferior[2];
  (* module_not_derived = 32'd1 *)
  (* src = "FIFO_estruct.v:21.17-30.2" *)
  true_dpram_sclk_estruct memory (
    .addr_ra(rd_ptr),
    .addr_wa(wr_ptr),
    .clk(clk),
    .data_a(data_in),
    .q_a(data_out),
    .re_a(re_a),
    .state(state),
    .we_a(we_a)
  );
endmodule

(* src = "true_dpram_sclk_estruct.v:11.1-66.10" *)
module true_dpram_sclk_estruct(data_a, addr_wa, addr_ra, we_a, re_a, clk, state, q_a);
  wire _0000_;
  wire _0001_;
  wire _0002_;
  wire _0003_;
  wire _0004_;
  wire _0005_;
  wire _0006_;
  wire _0007_;
  wire _0008_;
  wire _0009_;
  wire _0010_;
  wire _0011_;
  wire _0012_;
  wire _0013_;
  wire _0014_;
  wire _0015_;
  wire _0016_;
  wire _0017_;
  wire _0018_;
  wire _0019_;
  wire _0020_;
  wire _0021_;
  wire _0022_;
  wire _0023_;
  wire _0024_;
  wire _0025_;
  wire _0026_;
  wire _0027_;
  wire _0028_;
  wire _0029_;
  wire _0030_;
  wire _0031_;
  wire _0032_;
  wire _0033_;
  wire _0034_;
  wire _0035_;
  wire _0036_;
  wire _0037_;
  wire _0038_;
  wire _0039_;
  wire _0040_;
  wire _0041_;
  wire _0042_;
  wire _0043_;
  wire _0044_;
  wire _0045_;
  wire _0046_;
  wire _0047_;
  wire _0048_;
  wire _0049_;
  wire _0050_;
  wire _0051_;
  wire _0052_;
  wire _0053_;
  wire _0054_;
  wire _0055_;
  wire _0056_;
  wire _0057_;
  wire _0058_;
  wire _0059_;
  wire _0060_;
  wire _0061_;
  wire _0062_;
  wire _0063_;
  wire _0064_;
  wire _0065_;
  wire _0066_;
  wire _0067_;
  wire _0068_;
  wire _0069_;
  wire _0070_;
  wire _0071_;
  wire _0072_;
  wire _0073_;
  wire _0074_;
  wire _0075_;
  wire _0076_;
  wire _0077_;
  wire _0078_;
  wire _0079_;
  wire _0080_;
  wire _0081_;
  wire _0082_;
  wire _0083_;
  wire _0084_;
  wire _0085_;
  wire _0086_;
  wire _0087_;
  wire _0088_;
  wire _0089_;
  wire _0090_;
  wire _0091_;
  wire _0092_;
  wire _0093_;
  wire _0094_;
  wire _0095_;
  wire _0096_;
  wire _0097_;
  wire _0098_;
  wire _0099_;
  wire _0100_;
  wire _0101_;
  wire _0102_;
  wire _0103_;
  wire _0104_;
  wire _0105_;
  wire _0106_;
  wire _0107_;
  wire _0108_;
  wire _0109_;
  wire _0110_;
  wire _0111_;
  wire _0112_;
  wire _0113_;
  wire _0114_;
  wire _0115_;
  wire _0116_;
  wire _0117_;
  wire _0118_;
  wire _0119_;
  wire _0120_;
  wire _0121_;
  wire _0122_;
  wire _0123_;
  wire _0124_;
  wire _0125_;
  wire _0126_;
  wire _0127_;
  wire _0128_;
  wire _0129_;
  wire _0130_;
  wire _0131_;
  wire _0132_;
  wire _0133_;
  wire _0134_;
  wire _0135_;
  wire _0136_;
  wire _0137_;
  wire _0138_;
  wire _0139_;
  wire _0140_;
  wire _0141_;
  wire _0142_;
  wire _0143_;
  wire _0144_;
  wire _0145_;
  wire _0146_;
  wire _0147_;
  wire _0148_;
  wire _0149_;
  wire _0150_;
  wire _0151_;
  wire _0152_;
  wire _0153_;
  wire _0154_;
  wire _0155_;
  wire _0156_;
  wire _0157_;
  wire _0158_;
  wire _0159_;
  wire _0160_;
  wire _0161_;
  wire _0162_;
  wire _0163_;
  wire _0164_;
  wire _0165_;
  wire _0166_;
  wire _0167_;
  wire _0168_;
  wire _0169_;
  wire _0170_;
  wire _0171_;
  wire _0172_;
  wire _0173_;
  wire _0174_;
  wire _0175_;
  wire _0176_;
  wire _0177_;
  wire _0178_;
  wire _0179_;
  wire _0180_;
  wire _0181_;
  wire _0182_;
  wire _0183_;
  wire _0184_;
  wire _0185_;
  wire _0186_;
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire _0190_;
  wire _0191_;
  wire _0192_;
  wire _0193_;
  wire _0194_;
  wire _0195_;
  wire _0196_;
  wire _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire _0215_;
  wire _0216_;
  wire _0217_;
  wire _0218_;
  wire _0219_;
  wire _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire _0229_;
  wire _0230_;
  wire _0231_;
  wire _0232_;
  wire _0233_;
  wire _0234_;
  wire _0235_;
  wire _0236_;
  wire _0237_;
  wire _0238_;
  wire _0239_;
  wire _0240_;
  wire _0241_;
  wire _0242_;
  wire _0243_;
  wire _0244_;
  wire _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire _0261_;
  wire _0262_;
  wire _0263_;
  wire _0264_;
  wire _0265_;
  wire _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire _0275_;
  wire _0276_;
  wire _0277_;
  wire _0278_;
  wire _0279_;
  wire _0280_;
  wire _0281_;
  wire _0282_;
  wire _0283_;
  wire _0284_;
  wire _0285_;
  wire _0286_;
  wire _0287_;
  wire _0288_;
  wire _0289_;
  wire _0290_;
  wire _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire _0307_;
  wire _0308_;
  wire _0309_;
  wire _0310_;
  wire _0311_;
  wire _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire _0321_;
  wire _0322_;
  wire _0323_;
  wire _0324_;
  wire _0325_;
  wire _0326_;
  wire _0327_;
  wire _0328_;
  wire _0329_;
  wire _0330_;
  wire _0331_;
  wire _0332_;
  wire _0333_;
  wire _0334_;
  wire _0335_;
  wire _0336_;
  wire _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  wire _0346_;
  wire _0347_;
  wire _0348_;
  wire _0349_;
  wire _0350_;
  wire _0351_;
  wire _0352_;
  wire _0353_;
  wire _0354_;
  wire _0355_;
  wire _0356_;
  wire _0357_;
  wire _0358_;
  wire _0359_;
  wire _0360_;
  wire _0361_;
  wire _0362_;
  wire _0363_;
  wire _0364_;
  wire _0365_;
  wire _0366_;
  wire _0367_;
  wire _0368_;
  wire _0369_;
  wire _0370_;
  wire _0371_;
  wire _0372_;
  wire _0373_;
  wire _0374_;
  wire _0375_;
  wire _0376_;
  wire _0377_;
  wire _0378_;
  wire _0379_;
  wire _0380_;
  wire _0381_;
  wire _0382_;
  wire _0383_;
  wire _0384_;
  wire _0385_;
  wire _0386_;
  wire _0387_;
  wire _0388_;
  wire _0389_;
  wire _0390_;
  wire _0391_;
  wire _0392_;
  wire _0393_;
  wire _0394_;
  wire _0395_;
  wire _0396_;
  wire _0397_;
  wire _0398_;
  wire _0399_;
  wire _0400_;
  wire _0401_;
  wire _0402_;
  wire _0403_;
  wire _0404_;
  wire _0405_;
  wire _0406_;
  wire _0407_;
  wire _0408_;
  wire _0409_;
  wire _0410_;
  wire _0411_;
  wire _0412_;
  wire _0413_;
  wire _0414_;
  wire _0415_;
  wire _0416_;
  wire _0417_;
  wire _0418_;
  wire _0419_;
  wire _0420_;
  wire _0421_;
  wire _0422_;
  wire _0423_;
  wire _0424_;
  wire _0425_;
  wire _0426_;
  wire _0427_;
  wire _0428_;
  wire _0429_;
  wire _0430_;
  wire _0431_;
  wire _0432_;
  wire _0433_;
  wire _0434_;
  wire _0435_;
  wire _0436_;
  wire _0437_;
  wire _0438_;
  wire _0439_;
  wire _0440_;
  wire _0441_;
  wire _0442_;
  wire _0443_;
  wire _0444_;
  wire _0445_;
  wire _0446_;
  wire _0447_;
  wire _0448_;
  wire _0449_;
  wire _0450_;
  wire _0451_;
  wire _0452_;
  wire _0453_;
  wire _0454_;
  wire _0455_;
  wire _0456_;
  wire _0457_;
  wire _0458_;
  wire _0459_;
  wire _0460_;
  wire _0461_;
  wire _0462_;
  wire _0463_;
  wire _0464_;
  wire _0465_;
  wire _0466_;
  wire _0467_;
  wire _0468_;
  wire _0469_;
  wire _0470_;
  wire _0471_;
  wire _0472_;
  wire _0473_;
  wire _0474_;
  wire _0475_;
  wire _0476_;
  wire _0477_;
  wire _0478_;
  wire _0479_;
  wire _0480_;
  wire _0481_;
  wire _0482_;
  wire _0483_;
  wire _0484_;
  wire _0485_;
  wire _0486_;
  wire _0487_;
  wire _0488_;
  wire _0489_;
  wire _0490_;
  wire _0491_;
  wire _0492_;
  wire _0493_;
  wire _0494_;
  wire _0495_;
  wire _0496_;
  wire _0497_;
  wire _0498_;
  wire _0499_;
  wire _0500_;
  wire _0501_;
  wire _0502_;
  wire _0503_;
  wire _0504_;
  wire _0505_;
  wire _0506_;
  wire _0507_;
  wire _0508_;
  wire _0509_;
  wire _0510_;
  wire _0511_;
  wire _0512_;
  wire _0513_;
  wire _0514_;
  wire _0515_;
  wire _0516_;
  wire _0517_;
  wire _0518_;
  wire _0519_;
  wire _0520_;
  wire _0521_;
  wire _0522_;
  wire _0523_;
  wire _0524_;
  wire _0525_;
  wire _0526_;
  wire _0527_;
  wire _0528_;
  wire _0529_;
  wire _0530_;
  wire _0531_;
  wire _0532_;
  wire _0533_;
  wire _0534_;
  wire _0535_;
  wire _0536_;
  wire _0537_;
  wire _0538_;
  wire _0539_;
  wire _0540_;
  wire _0541_;
  wire _0542_;
  wire _0543_;
  wire _0544_;
  wire _0545_;
  wire _0546_;
  wire _0547_;
  wire _0548_;
  wire _0549_;
  wire _0550_;
  wire _0551_;
  wire _0552_;
  wire _0553_;
  wire _0554_;
  wire _0555_;
  wire _0556_;
  wire _0557_;
  wire _0558_;
  wire _0559_;
  wire _0560_;
  wire _0561_;
  wire _0562_;
  wire _0563_;
  wire _0564_;
  wire _0565_;
  wire _0566_;
  wire _0567_;
  wire _0568_;
  wire _0569_;
  wire _0570_;
  wire _0571_;
  wire _0572_;
  wire _0573_;
  wire _0574_;
  wire _0575_;
  wire _0576_;
  (* src = "true_dpram_sclk_estruct.v:16.17-16.24" *)
  input [2:0] addr_ra;
  (* src = "true_dpram_sclk_estruct.v:15.14-15.21" *)
  input [2:0] addr_wa;
  (* src = "true_dpram_sclk_estruct.v:21.8-21.11" *)
  input clk;
  (* src = "true_dpram_sclk_estruct.v:13.14-13.20" *)
  input [9:0] data_a;
  (* src = "true_dpram_sclk_estruct.v:23.19-23.22" *)
  output [9:0] q_a;
  wire [9:0] \ram[0] ;
  wire [9:0] \ram[1] ;
  wire [9:0] \ram[2] ;
  wire [9:0] \ram[3] ;
  wire [9:0] \ram[4] ;
  wire [9:0] \ram[5] ;
  wire [9:0] \ram[6] ;
  wire [9:0] \ram[7] ;
  (* src = "true_dpram_sclk_estruct.v:20.11-20.15" *)
  input re_a;
  (* src = "true_dpram_sclk_estruct.v:22.11-22.16" *)
  input state;
  (* src = "true_dpram_sclk_estruct.v:18.8-18.12" *)
  input we_a;
  NOT _0577_ (
    .A(\ram[4] [9]),
    .Y(_0090_)
  );
  NOT _0578_ (
    .A(\ram[4] [8]),
    .Y(_0091_)
  );
  NOT _0579_ (
    .A(\ram[4] [7]),
    .Y(_0092_)
  );
  NOT _0580_ (
    .A(\ram[4] [6]),
    .Y(_0093_)
  );
  NOT _0581_ (
    .A(\ram[4] [5]),
    .Y(_0094_)
  );
  NOT _0582_ (
    .A(\ram[4] [4]),
    .Y(_0095_)
  );
  NOT _0583_ (
    .A(\ram[4] [3]),
    .Y(_0096_)
  );
  NOT _0584_ (
    .A(\ram[4] [2]),
    .Y(_0097_)
  );
  NOT _0585_ (
    .A(\ram[4] [1]),
    .Y(_0098_)
  );
  NOT _0586_ (
    .A(\ram[4] [0]),
    .Y(_0099_)
  );
  NOT _0587_ (
    .A(\ram[5] [9]),
    .Y(_0100_)
  );
  NOT _0588_ (
    .A(\ram[5] [8]),
    .Y(_0101_)
  );
  NOT _0589_ (
    .A(\ram[5] [7]),
    .Y(_0102_)
  );
  NOT _0590_ (
    .A(\ram[5] [6]),
    .Y(_0103_)
  );
  NOT _0591_ (
    .A(\ram[5] [5]),
    .Y(_0104_)
  );
  NOT _0592_ (
    .A(\ram[5] [4]),
    .Y(_0105_)
  );
  NOT _0593_ (
    .A(\ram[5] [3]),
    .Y(_0106_)
  );
  NOT _0594_ (
    .A(\ram[5] [2]),
    .Y(_0107_)
  );
  NOT _0595_ (
    .A(\ram[5] [1]),
    .Y(_0108_)
  );
  NOT _0596_ (
    .A(\ram[5] [0]),
    .Y(_0109_)
  );
  NOT _0597_ (
    .A(\ram[6] [9]),
    .Y(_0110_)
  );
  NOT _0598_ (
    .A(\ram[6] [8]),
    .Y(_0111_)
  );
  NOT _0599_ (
    .A(\ram[6] [7]),
    .Y(_0112_)
  );
  NOT _0600_ (
    .A(\ram[6] [6]),
    .Y(_0113_)
  );
  NOT _0601_ (
    .A(\ram[6] [5]),
    .Y(_0114_)
  );
  NOT _0602_ (
    .A(\ram[6] [4]),
    .Y(_0115_)
  );
  NOT _0603_ (
    .A(\ram[6] [3]),
    .Y(_0116_)
  );
  NOT _0604_ (
    .A(\ram[6] [2]),
    .Y(_0117_)
  );
  NOT _0605_ (
    .A(\ram[6] [1]),
    .Y(_0118_)
  );
  NOT _0606_ (
    .A(\ram[6] [0]),
    .Y(_0119_)
  );
  NOT _0607_ (
    .A(\ram[7] [9]),
    .Y(_0120_)
  );
  NOT _0608_ (
    .A(\ram[7] [8]),
    .Y(_0121_)
  );
  NOT _0609_ (
    .A(\ram[7] [7]),
    .Y(_0122_)
  );
  NOT _0610_ (
    .A(\ram[7] [6]),
    .Y(_0123_)
  );
  NOT _0611_ (
    .A(\ram[7] [5]),
    .Y(_0124_)
  );
  NOT _0612_ (
    .A(\ram[7] [4]),
    .Y(_0125_)
  );
  NOT _0613_ (
    .A(\ram[7] [3]),
    .Y(_0126_)
  );
  NOT _0614_ (
    .A(\ram[7] [2]),
    .Y(_0127_)
  );
  NOT _0615_ (
    .A(\ram[7] [1]),
    .Y(_0128_)
  );
  NOT _0616_ (
    .A(\ram[7] [0]),
    .Y(_0129_)
  );
  NOT _0617_ (
    .A(state),
    .Y(_0130_)
  );
  NOT _0618_ (
    .A(addr_ra[1]),
    .Y(_0131_)
  );
  NOT _0619_ (
    .A(data_a[0]),
    .Y(_0132_)
  );
  NOT _0620_ (
    .A(we_a),
    .Y(_0133_)
  );
  NOT _0621_ (
    .A(data_a[1]),
    .Y(_0134_)
  );
  NOT _0622_ (
    .A(data_a[2]),
    .Y(_0135_)
  );
  NOT _0623_ (
    .A(data_a[3]),
    .Y(_0136_)
  );
  NOT _0624_ (
    .A(data_a[4]),
    .Y(_0137_)
  );
  NOT _0625_ (
    .A(data_a[5]),
    .Y(_0138_)
  );
  NOT _0626_ (
    .A(data_a[6]),
    .Y(_0139_)
  );
  NOT _0627_ (
    .A(data_a[7]),
    .Y(_0140_)
  );
  NOT _0628_ (
    .A(data_a[8]),
    .Y(_0141_)
  );
  NOT _0629_ (
    .A(data_a[9]),
    .Y(_0142_)
  );
  NOT _0630_ (
    .A(addr_wa[0]),
    .Y(_0143_)
  );
  NOT _0631_ (
    .A(addr_wa[1]),
    .Y(_0144_)
  );
  NOT _0632_ (
    .A(addr_wa[2]),
    .Y(_0145_)
  );
  NAND _0633_ (
    .A(re_a),
    .B(state),
    .Y(_0146_)
  );
  NAND _0634_ (
    .A(_0121_),
    .B(addr_ra[2]),
    .Y(_0147_)
  );
  NOR _0635_ (
    .A(\ram[3] [8]),
    .B(addr_ra[2]),
    .Y(_0148_)
  );
  NAND _0636_ (
    .A(addr_ra[0]),
    .B(_0147_),
    .Y(_0149_)
  );
  NOR _0637_ (
    .A(_0148_),
    .B(_0149_),
    .Y(_0150_)
  );
  NOR _0638_ (
    .A(\ram[2] [8]),
    .B(addr_ra[2]),
    .Y(_0151_)
  );
  NOT _0639_ (
    .A(_0151_),
    .Y(_0152_)
  );
  NAND _0640_ (
    .A(_0111_),
    .B(addr_ra[2]),
    .Y(_0153_)
  );
  NAND _0641_ (
    .A(_0152_),
    .B(_0153_),
    .Y(_0154_)
  );
  NOR _0642_ (
    .A(addr_ra[0]),
    .B(_0154_),
    .Y(_0155_)
  );
  NOR _0643_ (
    .A(_0150_),
    .B(_0155_),
    .Y(_0156_)
  );
  NOR _0644_ (
    .A(_0131_),
    .B(_0156_),
    .Y(_0157_)
  );
  NAND _0645_ (
    .A(_0101_),
    .B(addr_ra[2]),
    .Y(_0158_)
  );
  NOR _0646_ (
    .A(\ram[1] [8]),
    .B(addr_ra[2]),
    .Y(_0159_)
  );
  NAND _0647_ (
    .A(addr_ra[0]),
    .B(_0158_),
    .Y(_0160_)
  );
  NOR _0648_ (
    .A(_0159_),
    .B(_0160_),
    .Y(_0161_)
  );
  NOR _0649_ (
    .A(\ram[0] [8]),
    .B(addr_ra[2]),
    .Y(_0162_)
  );
  NOT _0650_ (
    .A(_0162_),
    .Y(_0163_)
  );
  NAND _0651_ (
    .A(_0091_),
    .B(addr_ra[2]),
    .Y(_0164_)
  );
  NAND _0652_ (
    .A(_0163_),
    .B(_0164_),
    .Y(_0165_)
  );
  NOR _0653_ (
    .A(addr_ra[0]),
    .B(_0165_),
    .Y(_0166_)
  );
  NOR _0654_ (
    .A(_0161_),
    .B(_0166_),
    .Y(_0167_)
  );
  NOR _0655_ (
    .A(addr_ra[1]),
    .B(_0167_),
    .Y(_0168_)
  );
  NOR _0656_ (
    .A(_0157_),
    .B(_0168_),
    .Y(_0169_)
  );
  NOR _0657_ (
    .A(_0146_),
    .B(_0169_),
    .Y(_0088_)
  );
  NAND _0658_ (
    .A(_0122_),
    .B(addr_ra[2]),
    .Y(_0170_)
  );
  NOR _0659_ (
    .A(\ram[3] [7]),
    .B(addr_ra[2]),
    .Y(_0171_)
  );
  NAND _0660_ (
    .A(addr_ra[0]),
    .B(_0170_),
    .Y(_0172_)
  );
  NOR _0661_ (
    .A(_0171_),
    .B(_0172_),
    .Y(_0173_)
  );
  NOR _0662_ (
    .A(\ram[2] [7]),
    .B(addr_ra[2]),
    .Y(_0174_)
  );
  NOT _0663_ (
    .A(_0174_),
    .Y(_0175_)
  );
  NAND _0664_ (
    .A(_0112_),
    .B(addr_ra[2]),
    .Y(_0176_)
  );
  NAND _0665_ (
    .A(_0175_),
    .B(_0176_),
    .Y(_0177_)
  );
  NOR _0666_ (
    .A(addr_ra[0]),
    .B(_0177_),
    .Y(_0178_)
  );
  NOR _0667_ (
    .A(_0173_),
    .B(_0178_),
    .Y(_0179_)
  );
  NOR _0668_ (
    .A(_0131_),
    .B(_0179_),
    .Y(_0180_)
  );
  NAND _0669_ (
    .A(_0102_),
    .B(addr_ra[2]),
    .Y(_0181_)
  );
  NOR _0670_ (
    .A(\ram[1] [7]),
    .B(addr_ra[2]),
    .Y(_0182_)
  );
  NAND _0671_ (
    .A(addr_ra[0]),
    .B(_0181_),
    .Y(_0183_)
  );
  NOR _0672_ (
    .A(_0182_),
    .B(_0183_),
    .Y(_0184_)
  );
  NOR _0673_ (
    .A(\ram[0] [7]),
    .B(addr_ra[2]),
    .Y(_0185_)
  );
  NOT _0674_ (
    .A(_0185_),
    .Y(_0186_)
  );
  NAND _0675_ (
    .A(_0092_),
    .B(addr_ra[2]),
    .Y(_0187_)
  );
  NAND _0676_ (
    .A(_0186_),
    .B(_0187_),
    .Y(_0188_)
  );
  NOR _0677_ (
    .A(addr_ra[0]),
    .B(_0188_),
    .Y(_0189_)
  );
  NOR _0678_ (
    .A(_0184_),
    .B(_0189_),
    .Y(_0190_)
  );
  NOR _0679_ (
    .A(addr_ra[1]),
    .B(_0190_),
    .Y(_0191_)
  );
  NOR _0680_ (
    .A(_0180_),
    .B(_0191_),
    .Y(_0192_)
  );
  NOR _0681_ (
    .A(_0146_),
    .B(_0192_),
    .Y(_0087_)
  );
  NAND _0682_ (
    .A(_0123_),
    .B(addr_ra[2]),
    .Y(_0193_)
  );
  NOR _0683_ (
    .A(\ram[3] [6]),
    .B(addr_ra[2]),
    .Y(_0194_)
  );
  NAND _0684_ (
    .A(addr_ra[0]),
    .B(_0193_),
    .Y(_0195_)
  );
  NOR _0685_ (
    .A(_0194_),
    .B(_0195_),
    .Y(_0196_)
  );
  NOR _0686_ (
    .A(\ram[2] [6]),
    .B(addr_ra[2]),
    .Y(_0197_)
  );
  NOT _0687_ (
    .A(_0197_),
    .Y(_0198_)
  );
  NAND _0688_ (
    .A(_0113_),
    .B(addr_ra[2]),
    .Y(_0199_)
  );
  NAND _0689_ (
    .A(_0198_),
    .B(_0199_),
    .Y(_0200_)
  );
  NOR _0690_ (
    .A(addr_ra[0]),
    .B(_0200_),
    .Y(_0201_)
  );
  NOR _0691_ (
    .A(_0196_),
    .B(_0201_),
    .Y(_0202_)
  );
  NOR _0692_ (
    .A(_0131_),
    .B(_0202_),
    .Y(_0203_)
  );
  NAND _0693_ (
    .A(_0103_),
    .B(addr_ra[2]),
    .Y(_0204_)
  );
  NOR _0694_ (
    .A(\ram[1] [6]),
    .B(addr_ra[2]),
    .Y(_0205_)
  );
  NAND _0695_ (
    .A(addr_ra[0]),
    .B(_0204_),
    .Y(_0206_)
  );
  NOR _0696_ (
    .A(_0205_),
    .B(_0206_),
    .Y(_0207_)
  );
  NOR _0697_ (
    .A(\ram[0] [6]),
    .B(addr_ra[2]),
    .Y(_0208_)
  );
  NOT _0698_ (
    .A(_0208_),
    .Y(_0209_)
  );
  NAND _0699_ (
    .A(_0093_),
    .B(addr_ra[2]),
    .Y(_0210_)
  );
  NAND _0700_ (
    .A(_0209_),
    .B(_0210_),
    .Y(_0211_)
  );
  NOR _0701_ (
    .A(addr_ra[0]),
    .B(_0211_),
    .Y(_0212_)
  );
  NOR _0702_ (
    .A(_0207_),
    .B(_0212_),
    .Y(_0213_)
  );
  NOR _0703_ (
    .A(addr_ra[1]),
    .B(_0213_),
    .Y(_0214_)
  );
  NOR _0704_ (
    .A(_0203_),
    .B(_0214_),
    .Y(_0215_)
  );
  NOR _0705_ (
    .A(_0146_),
    .B(_0215_),
    .Y(_0086_)
  );
  NAND _0706_ (
    .A(_0124_),
    .B(addr_ra[2]),
    .Y(_0216_)
  );
  NOR _0707_ (
    .A(\ram[3] [5]),
    .B(addr_ra[2]),
    .Y(_0217_)
  );
  NAND _0708_ (
    .A(addr_ra[0]),
    .B(_0216_),
    .Y(_0218_)
  );
  NOR _0709_ (
    .A(_0217_),
    .B(_0218_),
    .Y(_0219_)
  );
  NOR _0710_ (
    .A(\ram[2] [5]),
    .B(addr_ra[2]),
    .Y(_0220_)
  );
  NOT _0711_ (
    .A(_0220_),
    .Y(_0221_)
  );
  NAND _0712_ (
    .A(_0114_),
    .B(addr_ra[2]),
    .Y(_0222_)
  );
  NAND _0713_ (
    .A(_0221_),
    .B(_0222_),
    .Y(_0223_)
  );
  NOR _0714_ (
    .A(addr_ra[0]),
    .B(_0223_),
    .Y(_0224_)
  );
  NOR _0715_ (
    .A(_0219_),
    .B(_0224_),
    .Y(_0225_)
  );
  NOR _0716_ (
    .A(_0131_),
    .B(_0225_),
    .Y(_0226_)
  );
  NAND _0717_ (
    .A(_0104_),
    .B(addr_ra[2]),
    .Y(_0227_)
  );
  NOR _0718_ (
    .A(\ram[1] [5]),
    .B(addr_ra[2]),
    .Y(_0228_)
  );
  NAND _0719_ (
    .A(addr_ra[0]),
    .B(_0227_),
    .Y(_0229_)
  );
  NOR _0720_ (
    .A(_0228_),
    .B(_0229_),
    .Y(_0230_)
  );
  NOR _0721_ (
    .A(\ram[0] [5]),
    .B(addr_ra[2]),
    .Y(_0231_)
  );
  NOT _0722_ (
    .A(_0231_),
    .Y(_0232_)
  );
  NAND _0723_ (
    .A(_0094_),
    .B(addr_ra[2]),
    .Y(_0233_)
  );
  NAND _0724_ (
    .A(_0232_),
    .B(_0233_),
    .Y(_0234_)
  );
  NOR _0725_ (
    .A(addr_ra[0]),
    .B(_0234_),
    .Y(_0235_)
  );
  NOR _0726_ (
    .A(_0230_),
    .B(_0235_),
    .Y(_0236_)
  );
  NOR _0727_ (
    .A(addr_ra[1]),
    .B(_0236_),
    .Y(_0237_)
  );
  NOR _0728_ (
    .A(_0226_),
    .B(_0237_),
    .Y(_0238_)
  );
  NOR _0729_ (
    .A(_0146_),
    .B(_0238_),
    .Y(_0085_)
  );
  NAND _0730_ (
    .A(_0125_),
    .B(addr_ra[2]),
    .Y(_0239_)
  );
  NOR _0731_ (
    .A(\ram[3] [4]),
    .B(addr_ra[2]),
    .Y(_0240_)
  );
  NAND _0732_ (
    .A(addr_ra[0]),
    .B(_0239_),
    .Y(_0241_)
  );
  NOR _0733_ (
    .A(_0240_),
    .B(_0241_),
    .Y(_0242_)
  );
  NOR _0734_ (
    .A(\ram[2] [4]),
    .B(addr_ra[2]),
    .Y(_0243_)
  );
  NOT _0735_ (
    .A(_0243_),
    .Y(_0244_)
  );
  NAND _0736_ (
    .A(_0115_),
    .B(addr_ra[2]),
    .Y(_0245_)
  );
  NAND _0737_ (
    .A(_0244_),
    .B(_0245_),
    .Y(_0246_)
  );
  NOR _0738_ (
    .A(addr_ra[0]),
    .B(_0246_),
    .Y(_0247_)
  );
  NOR _0739_ (
    .A(_0242_),
    .B(_0247_),
    .Y(_0248_)
  );
  NOR _0740_ (
    .A(_0131_),
    .B(_0248_),
    .Y(_0249_)
  );
  NAND _0741_ (
    .A(_0105_),
    .B(addr_ra[2]),
    .Y(_0250_)
  );
  NOR _0742_ (
    .A(\ram[1] [4]),
    .B(addr_ra[2]),
    .Y(_0251_)
  );
  NAND _0743_ (
    .A(addr_ra[0]),
    .B(_0250_),
    .Y(_0252_)
  );
  NOR _0744_ (
    .A(_0251_),
    .B(_0252_),
    .Y(_0253_)
  );
  NOR _0745_ (
    .A(\ram[0] [4]),
    .B(addr_ra[2]),
    .Y(_0254_)
  );
  NOT _0746_ (
    .A(_0254_),
    .Y(_0255_)
  );
  NAND _0747_ (
    .A(_0095_),
    .B(addr_ra[2]),
    .Y(_0256_)
  );
  NAND _0748_ (
    .A(_0255_),
    .B(_0256_),
    .Y(_0257_)
  );
  NOR _0749_ (
    .A(addr_ra[0]),
    .B(_0257_),
    .Y(_0258_)
  );
  NOR _0750_ (
    .A(_0253_),
    .B(_0258_),
    .Y(_0259_)
  );
  NOR _0751_ (
    .A(addr_ra[1]),
    .B(_0259_),
    .Y(_0260_)
  );
  NOR _0752_ (
    .A(_0249_),
    .B(_0260_),
    .Y(_0261_)
  );
  NOR _0753_ (
    .A(_0146_),
    .B(_0261_),
    .Y(_0084_)
  );
  NAND _0754_ (
    .A(_0126_),
    .B(addr_ra[2]),
    .Y(_0262_)
  );
  NOR _0755_ (
    .A(\ram[3] [3]),
    .B(addr_ra[2]),
    .Y(_0263_)
  );
  NAND _0756_ (
    .A(addr_ra[0]),
    .B(_0262_),
    .Y(_0264_)
  );
  NOR _0757_ (
    .A(_0263_),
    .B(_0264_),
    .Y(_0265_)
  );
  NOR _0758_ (
    .A(\ram[2] [3]),
    .B(addr_ra[2]),
    .Y(_0266_)
  );
  NOT _0759_ (
    .A(_0266_),
    .Y(_0267_)
  );
  NAND _0760_ (
    .A(_0116_),
    .B(addr_ra[2]),
    .Y(_0268_)
  );
  NAND _0761_ (
    .A(_0267_),
    .B(_0268_),
    .Y(_0269_)
  );
  NOR _0762_ (
    .A(addr_ra[0]),
    .B(_0269_),
    .Y(_0270_)
  );
  NOR _0763_ (
    .A(_0265_),
    .B(_0270_),
    .Y(_0271_)
  );
  NOR _0764_ (
    .A(_0131_),
    .B(_0271_),
    .Y(_0272_)
  );
  NAND _0765_ (
    .A(_0106_),
    .B(addr_ra[2]),
    .Y(_0273_)
  );
  NOR _0766_ (
    .A(\ram[1] [3]),
    .B(addr_ra[2]),
    .Y(_0274_)
  );
  NAND _0767_ (
    .A(addr_ra[0]),
    .B(_0273_),
    .Y(_0275_)
  );
  NOR _0768_ (
    .A(_0274_),
    .B(_0275_),
    .Y(_0276_)
  );
  NOR _0769_ (
    .A(\ram[0] [3]),
    .B(addr_ra[2]),
    .Y(_0277_)
  );
  NOT _0770_ (
    .A(_0277_),
    .Y(_0278_)
  );
  NAND _0771_ (
    .A(_0096_),
    .B(addr_ra[2]),
    .Y(_0279_)
  );
  NAND _0772_ (
    .A(_0278_),
    .B(_0279_),
    .Y(_0280_)
  );
  NOR _0773_ (
    .A(addr_ra[0]),
    .B(_0280_),
    .Y(_0281_)
  );
  NOR _0774_ (
    .A(_0276_),
    .B(_0281_),
    .Y(_0282_)
  );
  NOR _0775_ (
    .A(addr_ra[1]),
    .B(_0282_),
    .Y(_0283_)
  );
  NOR _0776_ (
    .A(_0272_),
    .B(_0283_),
    .Y(_0284_)
  );
  NOR _0777_ (
    .A(_0146_),
    .B(_0284_),
    .Y(_0083_)
  );
  NAND _0778_ (
    .A(_0127_),
    .B(addr_ra[2]),
    .Y(_0285_)
  );
  NOR _0779_ (
    .A(\ram[3] [2]),
    .B(addr_ra[2]),
    .Y(_0286_)
  );
  NAND _0780_ (
    .A(addr_ra[0]),
    .B(_0285_),
    .Y(_0287_)
  );
  NOR _0781_ (
    .A(_0286_),
    .B(_0287_),
    .Y(_0288_)
  );
  NOR _0782_ (
    .A(\ram[2] [2]),
    .B(addr_ra[2]),
    .Y(_0289_)
  );
  NOT _0783_ (
    .A(_0289_),
    .Y(_0290_)
  );
  NAND _0784_ (
    .A(_0117_),
    .B(addr_ra[2]),
    .Y(_0291_)
  );
  NAND _0785_ (
    .A(_0290_),
    .B(_0291_),
    .Y(_0292_)
  );
  NOR _0786_ (
    .A(addr_ra[0]),
    .B(_0292_),
    .Y(_0293_)
  );
  NOR _0787_ (
    .A(_0288_),
    .B(_0293_),
    .Y(_0294_)
  );
  NOR _0788_ (
    .A(_0131_),
    .B(_0294_),
    .Y(_0295_)
  );
  NAND _0789_ (
    .A(_0107_),
    .B(addr_ra[2]),
    .Y(_0296_)
  );
  NOR _0790_ (
    .A(\ram[1] [2]),
    .B(addr_ra[2]),
    .Y(_0297_)
  );
  NAND _0791_ (
    .A(addr_ra[0]),
    .B(_0296_),
    .Y(_0298_)
  );
  NOR _0792_ (
    .A(_0297_),
    .B(_0298_),
    .Y(_0299_)
  );
  NOR _0793_ (
    .A(\ram[0] [2]),
    .B(addr_ra[2]),
    .Y(_0300_)
  );
  NOT _0794_ (
    .A(_0300_),
    .Y(_0301_)
  );
  NAND _0795_ (
    .A(_0097_),
    .B(addr_ra[2]),
    .Y(_0302_)
  );
  NAND _0796_ (
    .A(_0301_),
    .B(_0302_),
    .Y(_0303_)
  );
  NOR _0797_ (
    .A(addr_ra[0]),
    .B(_0303_),
    .Y(_0304_)
  );
  NOR _0798_ (
    .A(_0299_),
    .B(_0304_),
    .Y(_0305_)
  );
  NOR _0799_ (
    .A(addr_ra[1]),
    .B(_0305_),
    .Y(_0306_)
  );
  NOR _0800_ (
    .A(_0295_),
    .B(_0306_),
    .Y(_0307_)
  );
  NOR _0801_ (
    .A(_0146_),
    .B(_0307_),
    .Y(_0082_)
  );
  NAND _0802_ (
    .A(_0128_),
    .B(addr_ra[2]),
    .Y(_0308_)
  );
  NOR _0803_ (
    .A(\ram[3] [1]),
    .B(addr_ra[2]),
    .Y(_0309_)
  );
  NAND _0804_ (
    .A(addr_ra[0]),
    .B(_0308_),
    .Y(_0310_)
  );
  NOR _0805_ (
    .A(_0309_),
    .B(_0310_),
    .Y(_0311_)
  );
  NOR _0806_ (
    .A(\ram[2] [1]),
    .B(addr_ra[2]),
    .Y(_0312_)
  );
  NOT _0807_ (
    .A(_0312_),
    .Y(_0313_)
  );
  NAND _0808_ (
    .A(_0118_),
    .B(addr_ra[2]),
    .Y(_0314_)
  );
  NAND _0809_ (
    .A(_0313_),
    .B(_0314_),
    .Y(_0315_)
  );
  NOR _0810_ (
    .A(addr_ra[0]),
    .B(_0315_),
    .Y(_0316_)
  );
  NOR _0811_ (
    .A(_0311_),
    .B(_0316_),
    .Y(_0317_)
  );
  NOR _0812_ (
    .A(_0131_),
    .B(_0317_),
    .Y(_0318_)
  );
  NAND _0813_ (
    .A(_0108_),
    .B(addr_ra[2]),
    .Y(_0319_)
  );
  NOR _0814_ (
    .A(\ram[1] [1]),
    .B(addr_ra[2]),
    .Y(_0320_)
  );
  NAND _0815_ (
    .A(addr_ra[0]),
    .B(_0319_),
    .Y(_0321_)
  );
  NOR _0816_ (
    .A(_0320_),
    .B(_0321_),
    .Y(_0322_)
  );
  NOR _0817_ (
    .A(\ram[0] [1]),
    .B(addr_ra[2]),
    .Y(_0323_)
  );
  NOT _0818_ (
    .A(_0323_),
    .Y(_0324_)
  );
  NAND _0819_ (
    .A(_0098_),
    .B(addr_ra[2]),
    .Y(_0325_)
  );
  NAND _0820_ (
    .A(_0324_),
    .B(_0325_),
    .Y(_0326_)
  );
  NOR _0821_ (
    .A(addr_ra[0]),
    .B(_0326_),
    .Y(_0327_)
  );
  NOR _0822_ (
    .A(_0322_),
    .B(_0327_),
    .Y(_0328_)
  );
  NOR _0823_ (
    .A(addr_ra[1]),
    .B(_0328_),
    .Y(_0329_)
  );
  NOR _0824_ (
    .A(_0318_),
    .B(_0329_),
    .Y(_0330_)
  );
  NOR _0825_ (
    .A(_0146_),
    .B(_0330_),
    .Y(_0081_)
  );
  NAND _0826_ (
    .A(_0129_),
    .B(addr_ra[2]),
    .Y(_0331_)
  );
  NOR _0827_ (
    .A(\ram[3] [0]),
    .B(addr_ra[2]),
    .Y(_0332_)
  );
  NAND _0828_ (
    .A(addr_ra[0]),
    .B(_0331_),
    .Y(_0333_)
  );
  NOR _0829_ (
    .A(_0332_),
    .B(_0333_),
    .Y(_0334_)
  );
  NOR _0830_ (
    .A(\ram[2] [0]),
    .B(addr_ra[2]),
    .Y(_0335_)
  );
  NOT _0831_ (
    .A(_0335_),
    .Y(_0336_)
  );
  NAND _0832_ (
    .A(_0119_),
    .B(addr_ra[2]),
    .Y(_0337_)
  );
  NAND _0833_ (
    .A(_0336_),
    .B(_0337_),
    .Y(_0338_)
  );
  NOR _0834_ (
    .A(addr_ra[0]),
    .B(_0338_),
    .Y(_0339_)
  );
  NOR _0835_ (
    .A(_0334_),
    .B(_0339_),
    .Y(_0340_)
  );
  NOR _0836_ (
    .A(_0131_),
    .B(_0340_),
    .Y(_0341_)
  );
  NAND _0837_ (
    .A(_0109_),
    .B(addr_ra[2]),
    .Y(_0342_)
  );
  NOR _0838_ (
    .A(\ram[1] [0]),
    .B(addr_ra[2]),
    .Y(_0343_)
  );
  NAND _0839_ (
    .A(addr_ra[0]),
    .B(_0342_),
    .Y(_0344_)
  );
  NOR _0840_ (
    .A(_0343_),
    .B(_0344_),
    .Y(_0345_)
  );
  NOR _0841_ (
    .A(\ram[0] [0]),
    .B(addr_ra[2]),
    .Y(_0346_)
  );
  NOT _0842_ (
    .A(_0346_),
    .Y(_0347_)
  );
  NAND _0843_ (
    .A(_0099_),
    .B(addr_ra[2]),
    .Y(_0348_)
  );
  NAND _0844_ (
    .A(_0347_),
    .B(_0348_),
    .Y(_0349_)
  );
  NOR _0845_ (
    .A(addr_ra[0]),
    .B(_0349_),
    .Y(_0350_)
  );
  NOR _0846_ (
    .A(_0345_),
    .B(_0350_),
    .Y(_0351_)
  );
  NOR _0847_ (
    .A(addr_ra[1]),
    .B(_0351_),
    .Y(_0352_)
  );
  NOR _0848_ (
    .A(_0341_),
    .B(_0352_),
    .Y(_0353_)
  );
  NOR _0849_ (
    .A(_0146_),
    .B(_0353_),
    .Y(_0080_)
  );
  NOR _0850_ (
    .A(_0130_),
    .B(_0133_),
    .Y(_0354_)
  );
  NAND _0851_ (
    .A(state),
    .B(we_a),
    .Y(_0355_)
  );
  NOR _0852_ (
    .A(addr_wa[2]),
    .B(_0355_),
    .Y(_0356_)
  );
  NOT _0853_ (
    .A(_0356_),
    .Y(_0357_)
  );
  NOR _0854_ (
    .A(_0145_),
    .B(_0355_),
    .Y(_0358_)
  );
  NAND _0855_ (
    .A(addr_wa[2]),
    .B(_0354_),
    .Y(_0359_)
  );
  NOR _0856_ (
    .A(addr_wa[1]),
    .B(_0357_),
    .Y(_0360_)
  );
  NAND _0857_ (
    .A(_0144_),
    .B(_0356_),
    .Y(_0361_)
  );
  NOR _0858_ (
    .A(addr_wa[0]),
    .B(_0361_),
    .Y(_0362_)
  );
  NAND _0859_ (
    .A(_0143_),
    .B(_0360_),
    .Y(_0363_)
  );
  NOR _0860_ (
    .A(\ram[0] [9]),
    .B(_0362_),
    .Y(_0364_)
  );
  NOR _0861_ (
    .A(data_a[9]),
    .B(_0363_),
    .Y(_0365_)
  );
  NOR _0862_ (
    .A(_0364_),
    .B(_0365_),
    .Y(_0079_)
  );
  NOR _0863_ (
    .A(\ram[0] [8]),
    .B(_0362_),
    .Y(_0366_)
  );
  NOR _0864_ (
    .A(data_a[8]),
    .B(_0363_),
    .Y(_0367_)
  );
  NOR _0865_ (
    .A(_0366_),
    .B(_0367_),
    .Y(_0078_)
  );
  NOR _0866_ (
    .A(\ram[0] [7]),
    .B(_0362_),
    .Y(_0368_)
  );
  NOR _0867_ (
    .A(data_a[7]),
    .B(_0363_),
    .Y(_0369_)
  );
  NOR _0868_ (
    .A(_0368_),
    .B(_0369_),
    .Y(_0077_)
  );
  NOR _0869_ (
    .A(\ram[0] [6]),
    .B(_0362_),
    .Y(_0370_)
  );
  NOR _0870_ (
    .A(data_a[6]),
    .B(_0363_),
    .Y(_0371_)
  );
  NOR _0871_ (
    .A(_0370_),
    .B(_0371_),
    .Y(_0076_)
  );
  NOR _0872_ (
    .A(\ram[0] [5]),
    .B(_0362_),
    .Y(_0372_)
  );
  NOR _0873_ (
    .A(data_a[5]),
    .B(_0363_),
    .Y(_0373_)
  );
  NOR _0874_ (
    .A(_0372_),
    .B(_0373_),
    .Y(_0075_)
  );
  NOR _0875_ (
    .A(\ram[0] [4]),
    .B(_0362_),
    .Y(_0374_)
  );
  NOR _0876_ (
    .A(data_a[4]),
    .B(_0363_),
    .Y(_0375_)
  );
  NOR _0877_ (
    .A(_0374_),
    .B(_0375_),
    .Y(_0074_)
  );
  NOR _0878_ (
    .A(\ram[0] [3]),
    .B(_0362_),
    .Y(_0376_)
  );
  NOR _0879_ (
    .A(data_a[3]),
    .B(_0363_),
    .Y(_0377_)
  );
  NOR _0880_ (
    .A(_0376_),
    .B(_0377_),
    .Y(_0073_)
  );
  NOR _0881_ (
    .A(\ram[0] [2]),
    .B(_0362_),
    .Y(_0378_)
  );
  NOR _0882_ (
    .A(data_a[2]),
    .B(_0363_),
    .Y(_0379_)
  );
  NOR _0883_ (
    .A(_0378_),
    .B(_0379_),
    .Y(_0072_)
  );
  NOR _0884_ (
    .A(\ram[0] [1]),
    .B(_0362_),
    .Y(_0380_)
  );
  NOR _0885_ (
    .A(data_a[1]),
    .B(_0363_),
    .Y(_0381_)
  );
  NOR _0886_ (
    .A(_0380_),
    .B(_0381_),
    .Y(_0071_)
  );
  NOR _0887_ (
    .A(\ram[0] [0]),
    .B(_0362_),
    .Y(_0382_)
  );
  NOR _0888_ (
    .A(data_a[0]),
    .B(_0363_),
    .Y(_0383_)
  );
  NOR _0889_ (
    .A(_0382_),
    .B(_0383_),
    .Y(_0070_)
  );
  NOR _0890_ (
    .A(_0143_),
    .B(_0361_),
    .Y(_0384_)
  );
  NAND _0891_ (
    .A(addr_wa[0]),
    .B(_0360_),
    .Y(_0385_)
  );
  NAND _0892_ (
    .A(data_a[9]),
    .B(_0384_),
    .Y(_0386_)
  );
  NAND _0893_ (
    .A(\ram[1] [9]),
    .B(_0385_),
    .Y(_0387_)
  );
  NAND _0894_ (
    .A(_0386_),
    .B(_0387_),
    .Y(_0069_)
  );
  NAND _0895_ (
    .A(data_a[8]),
    .B(_0384_),
    .Y(_0388_)
  );
  NAND _0896_ (
    .A(\ram[1] [8]),
    .B(_0385_),
    .Y(_0389_)
  );
  NAND _0897_ (
    .A(_0388_),
    .B(_0389_),
    .Y(_0068_)
  );
  NAND _0898_ (
    .A(data_a[7]),
    .B(_0384_),
    .Y(_0390_)
  );
  NAND _0899_ (
    .A(\ram[1] [7]),
    .B(_0385_),
    .Y(_0391_)
  );
  NAND _0900_ (
    .A(_0390_),
    .B(_0391_),
    .Y(_0067_)
  );
  NAND _0901_ (
    .A(data_a[6]),
    .B(_0384_),
    .Y(_0392_)
  );
  NAND _0902_ (
    .A(\ram[1] [6]),
    .B(_0385_),
    .Y(_0393_)
  );
  NAND _0903_ (
    .A(_0392_),
    .B(_0393_),
    .Y(_0066_)
  );
  NAND _0904_ (
    .A(data_a[5]),
    .B(_0384_),
    .Y(_0394_)
  );
  NAND _0905_ (
    .A(\ram[1] [5]),
    .B(_0385_),
    .Y(_0395_)
  );
  NAND _0906_ (
    .A(_0394_),
    .B(_0395_),
    .Y(_0065_)
  );
  NAND _0907_ (
    .A(data_a[4]),
    .B(_0384_),
    .Y(_0396_)
  );
  NAND _0908_ (
    .A(\ram[1] [4]),
    .B(_0385_),
    .Y(_0397_)
  );
  NAND _0909_ (
    .A(_0396_),
    .B(_0397_),
    .Y(_0064_)
  );
  NAND _0910_ (
    .A(data_a[3]),
    .B(_0384_),
    .Y(_0398_)
  );
  NAND _0911_ (
    .A(\ram[1] [3]),
    .B(_0385_),
    .Y(_0399_)
  );
  NAND _0912_ (
    .A(_0398_),
    .B(_0399_),
    .Y(_0063_)
  );
  NAND _0913_ (
    .A(data_a[2]),
    .B(_0384_),
    .Y(_0400_)
  );
  NAND _0914_ (
    .A(\ram[1] [2]),
    .B(_0385_),
    .Y(_0401_)
  );
  NAND _0915_ (
    .A(_0400_),
    .B(_0401_),
    .Y(_0062_)
  );
  NAND _0916_ (
    .A(data_a[1]),
    .B(_0384_),
    .Y(_0402_)
  );
  NAND _0917_ (
    .A(\ram[1] [1]),
    .B(_0385_),
    .Y(_0403_)
  );
  NAND _0918_ (
    .A(_0402_),
    .B(_0403_),
    .Y(_0061_)
  );
  NAND _0919_ (
    .A(data_a[0]),
    .B(_0384_),
    .Y(_0404_)
  );
  NAND _0920_ (
    .A(\ram[1] [0]),
    .B(_0385_),
    .Y(_0405_)
  );
  NAND _0921_ (
    .A(_0404_),
    .B(_0405_),
    .Y(_0060_)
  );
  NOR _0922_ (
    .A(_0144_),
    .B(_0357_),
    .Y(_0406_)
  );
  NAND _0923_ (
    .A(addr_wa[1]),
    .B(_0356_),
    .Y(_0407_)
  );
  NOR _0924_ (
    .A(addr_wa[0]),
    .B(_0407_),
    .Y(_0408_)
  );
  NAND _0925_ (
    .A(_0143_),
    .B(_0406_),
    .Y(_0409_)
  );
  NAND _0926_ (
    .A(data_a[9]),
    .B(_0408_),
    .Y(_0410_)
  );
  NAND _0927_ (
    .A(\ram[2] [9]),
    .B(_0409_),
    .Y(_0411_)
  );
  NOR _0928_ (
    .A(_0142_),
    .B(_0355_),
    .Y(_0412_)
  );
  NAND _0929_ (
    .A(_0410_),
    .B(_0411_),
    .Y(_0059_)
  );
  NAND _0930_ (
    .A(data_a[8]),
    .B(_0408_),
    .Y(_0413_)
  );
  NAND _0931_ (
    .A(\ram[2] [8]),
    .B(_0409_),
    .Y(_0414_)
  );
  NOR _0932_ (
    .A(_0141_),
    .B(_0355_),
    .Y(_0415_)
  );
  NAND _0933_ (
    .A(_0413_),
    .B(_0414_),
    .Y(_0058_)
  );
  NAND _0934_ (
    .A(data_a[7]),
    .B(_0408_),
    .Y(_0416_)
  );
  NAND _0935_ (
    .A(\ram[2] [7]),
    .B(_0409_),
    .Y(_0417_)
  );
  NOR _0936_ (
    .A(_0140_),
    .B(_0355_),
    .Y(_0418_)
  );
  NAND _0937_ (
    .A(_0416_),
    .B(_0417_),
    .Y(_0057_)
  );
  NAND _0938_ (
    .A(data_a[6]),
    .B(_0408_),
    .Y(_0419_)
  );
  NAND _0939_ (
    .A(\ram[2] [6]),
    .B(_0409_),
    .Y(_0420_)
  );
  NOR _0940_ (
    .A(_0139_),
    .B(_0355_),
    .Y(_0421_)
  );
  NAND _0941_ (
    .A(_0419_),
    .B(_0420_),
    .Y(_0056_)
  );
  NAND _0942_ (
    .A(data_a[5]),
    .B(_0408_),
    .Y(_0422_)
  );
  NAND _0943_ (
    .A(\ram[2] [5]),
    .B(_0409_),
    .Y(_0423_)
  );
  NOR _0944_ (
    .A(_0138_),
    .B(_0355_),
    .Y(_0424_)
  );
  NAND _0945_ (
    .A(_0422_),
    .B(_0423_),
    .Y(_0055_)
  );
  NAND _0946_ (
    .A(data_a[4]),
    .B(_0408_),
    .Y(_0425_)
  );
  NAND _0947_ (
    .A(\ram[2] [4]),
    .B(_0409_),
    .Y(_0426_)
  );
  NOR _0948_ (
    .A(_0137_),
    .B(_0355_),
    .Y(_0427_)
  );
  NAND _0949_ (
    .A(_0425_),
    .B(_0426_),
    .Y(_0054_)
  );
  NAND _0950_ (
    .A(data_a[3]),
    .B(_0408_),
    .Y(_0428_)
  );
  NAND _0951_ (
    .A(\ram[2] [3]),
    .B(_0409_),
    .Y(_0429_)
  );
  NOR _0952_ (
    .A(_0136_),
    .B(_0355_),
    .Y(_0430_)
  );
  NAND _0953_ (
    .A(_0428_),
    .B(_0429_),
    .Y(_0053_)
  );
  NAND _0954_ (
    .A(data_a[2]),
    .B(_0408_),
    .Y(_0431_)
  );
  NAND _0955_ (
    .A(\ram[2] [2]),
    .B(_0409_),
    .Y(_0432_)
  );
  NOR _0956_ (
    .A(_0135_),
    .B(_0355_),
    .Y(_0433_)
  );
  NAND _0957_ (
    .A(_0431_),
    .B(_0432_),
    .Y(_0052_)
  );
  NAND _0958_ (
    .A(data_a[1]),
    .B(_0408_),
    .Y(_0434_)
  );
  NAND _0959_ (
    .A(\ram[2] [1]),
    .B(_0409_),
    .Y(_0435_)
  );
  NOR _0960_ (
    .A(_0134_),
    .B(_0355_),
    .Y(_0436_)
  );
  NAND _0961_ (
    .A(_0434_),
    .B(_0435_),
    .Y(_0051_)
  );
  NAND _0962_ (
    .A(data_a[0]),
    .B(_0408_),
    .Y(_0437_)
  );
  NAND _0963_ (
    .A(\ram[2] [0]),
    .B(_0409_),
    .Y(_0438_)
  );
  NOR _0964_ (
    .A(_0132_),
    .B(_0355_),
    .Y(_0439_)
  );
  NAND _0965_ (
    .A(_0437_),
    .B(_0438_),
    .Y(_0050_)
  );
  NOR _0966_ (
    .A(_0143_),
    .B(_0407_),
    .Y(_0440_)
  );
  NAND _0967_ (
    .A(addr_wa[0]),
    .B(_0406_),
    .Y(_0441_)
  );
  NAND _0968_ (
    .A(data_a[9]),
    .B(_0440_),
    .Y(_0442_)
  );
  NAND _0969_ (
    .A(\ram[3] [9]),
    .B(_0441_),
    .Y(_0443_)
  );
  NAND _0970_ (
    .A(_0442_),
    .B(_0443_),
    .Y(_0049_)
  );
  NAND _0971_ (
    .A(data_a[8]),
    .B(_0440_),
    .Y(_0444_)
  );
  NAND _0972_ (
    .A(\ram[3] [8]),
    .B(_0441_),
    .Y(_0445_)
  );
  NAND _0973_ (
    .A(_0444_),
    .B(_0445_),
    .Y(_0048_)
  );
  NAND _0974_ (
    .A(data_a[7]),
    .B(_0440_),
    .Y(_0446_)
  );
  NAND _0975_ (
    .A(\ram[3] [7]),
    .B(_0441_),
    .Y(_0447_)
  );
  NAND _0976_ (
    .A(_0446_),
    .B(_0447_),
    .Y(_0047_)
  );
  NAND _0977_ (
    .A(data_a[6]),
    .B(_0440_),
    .Y(_0448_)
  );
  NAND _0978_ (
    .A(\ram[3] [6]),
    .B(_0441_),
    .Y(_0449_)
  );
  NAND _0979_ (
    .A(_0448_),
    .B(_0449_),
    .Y(_0046_)
  );
  NAND _0980_ (
    .A(data_a[5]),
    .B(_0440_),
    .Y(_0450_)
  );
  NAND _0981_ (
    .A(\ram[3] [5]),
    .B(_0441_),
    .Y(_0451_)
  );
  NAND _0982_ (
    .A(_0450_),
    .B(_0451_),
    .Y(_0045_)
  );
  NAND _0983_ (
    .A(data_a[4]),
    .B(_0440_),
    .Y(_0452_)
  );
  NAND _0984_ (
    .A(\ram[3] [4]),
    .B(_0441_),
    .Y(_0453_)
  );
  NAND _0985_ (
    .A(_0452_),
    .B(_0453_),
    .Y(_0044_)
  );
  NAND _0986_ (
    .A(data_a[3]),
    .B(_0440_),
    .Y(_0454_)
  );
  NAND _0987_ (
    .A(\ram[3] [3]),
    .B(_0441_),
    .Y(_0455_)
  );
  NAND _0988_ (
    .A(_0454_),
    .B(_0455_),
    .Y(_0043_)
  );
  NAND _0989_ (
    .A(data_a[2]),
    .B(_0440_),
    .Y(_0456_)
  );
  NAND _0990_ (
    .A(\ram[3] [2]),
    .B(_0441_),
    .Y(_0457_)
  );
  NAND _0991_ (
    .A(_0456_),
    .B(_0457_),
    .Y(_0042_)
  );
  NAND _0992_ (
    .A(data_a[1]),
    .B(_0440_),
    .Y(_0458_)
  );
  NAND _0993_ (
    .A(\ram[3] [1]),
    .B(_0441_),
    .Y(_0459_)
  );
  NAND _0994_ (
    .A(_0458_),
    .B(_0459_),
    .Y(_0041_)
  );
  NAND _0995_ (
    .A(data_a[0]),
    .B(_0440_),
    .Y(_0460_)
  );
  NAND _0996_ (
    .A(\ram[3] [0]),
    .B(_0441_),
    .Y(_0461_)
  );
  NAND _0997_ (
    .A(_0460_),
    .B(_0461_),
    .Y(_0040_)
  );
  NOR _0998_ (
    .A(addr_wa[1]),
    .B(_0359_),
    .Y(_0462_)
  );
  NAND _0999_ (
    .A(_0144_),
    .B(_0358_),
    .Y(_0463_)
  );
  NOR _1000_ (
    .A(addr_wa[0]),
    .B(_0463_),
    .Y(_0464_)
  );
  NAND _1001_ (
    .A(_0143_),
    .B(_0462_),
    .Y(_0465_)
  );
  NAND _1002_ (
    .A(_0412_),
    .B(_0464_),
    .Y(_0466_)
  );
  NAND _1003_ (
    .A(\ram[4] [9]),
    .B(_0465_),
    .Y(_0467_)
  );
  NAND _1004_ (
    .A(_0466_),
    .B(_0467_),
    .Y(_0039_)
  );
  NAND _1005_ (
    .A(\ram[4] [8]),
    .B(_0465_),
    .Y(_0468_)
  );
  NAND _1006_ (
    .A(_0415_),
    .B(_0464_),
    .Y(_0469_)
  );
  NAND _1007_ (
    .A(_0468_),
    .B(_0469_),
    .Y(_0038_)
  );
  NAND _1008_ (
    .A(\ram[4] [7]),
    .B(_0465_),
    .Y(_0470_)
  );
  NAND _1009_ (
    .A(_0418_),
    .B(_0464_),
    .Y(_0471_)
  );
  NAND _1010_ (
    .A(_0470_),
    .B(_0471_),
    .Y(_0037_)
  );
  NAND _1011_ (
    .A(\ram[4] [6]),
    .B(_0465_),
    .Y(_0472_)
  );
  NAND _1012_ (
    .A(_0421_),
    .B(_0464_),
    .Y(_0473_)
  );
  NAND _1013_ (
    .A(_0472_),
    .B(_0473_),
    .Y(_0036_)
  );
  NAND _1014_ (
    .A(\ram[4] [5]),
    .B(_0465_),
    .Y(_0474_)
  );
  NAND _1015_ (
    .A(_0424_),
    .B(_0464_),
    .Y(_0475_)
  );
  NAND _1016_ (
    .A(_0474_),
    .B(_0475_),
    .Y(_0035_)
  );
  NAND _1017_ (
    .A(\ram[4] [4]),
    .B(_0465_),
    .Y(_0476_)
  );
  NAND _1018_ (
    .A(_0427_),
    .B(_0464_),
    .Y(_0477_)
  );
  NAND _1019_ (
    .A(_0476_),
    .B(_0477_),
    .Y(_0034_)
  );
  NAND _1020_ (
    .A(_0430_),
    .B(_0464_),
    .Y(_0478_)
  );
  NAND _1021_ (
    .A(\ram[4] [3]),
    .B(_0465_),
    .Y(_0479_)
  );
  NAND _1022_ (
    .A(_0478_),
    .B(_0479_),
    .Y(_0033_)
  );
  NAND _1023_ (
    .A(\ram[4] [2]),
    .B(_0465_),
    .Y(_0480_)
  );
  NAND _1024_ (
    .A(_0433_),
    .B(_0464_),
    .Y(_0481_)
  );
  NAND _1025_ (
    .A(_0480_),
    .B(_0481_),
    .Y(_0032_)
  );
  NAND _1026_ (
    .A(\ram[4] [1]),
    .B(_0465_),
    .Y(_0482_)
  );
  NAND _1027_ (
    .A(_0436_),
    .B(_0464_),
    .Y(_0483_)
  );
  NAND _1028_ (
    .A(_0482_),
    .B(_0483_),
    .Y(_0031_)
  );
  NAND _1029_ (
    .A(\ram[4] [0]),
    .B(_0465_),
    .Y(_0484_)
  );
  NAND _1030_ (
    .A(_0439_),
    .B(_0464_),
    .Y(_0485_)
  );
  NAND _1031_ (
    .A(_0484_),
    .B(_0485_),
    .Y(_0030_)
  );
  NOR _1032_ (
    .A(_0143_),
    .B(_0463_),
    .Y(_0486_)
  );
  NAND _1033_ (
    .A(addr_wa[0]),
    .B(_0462_),
    .Y(_0487_)
  );
  NAND _1034_ (
    .A(_0412_),
    .B(_0486_),
    .Y(_0488_)
  );
  NAND _1035_ (
    .A(\ram[5] [9]),
    .B(_0487_),
    .Y(_0489_)
  );
  NAND _1036_ (
    .A(_0488_),
    .B(_0489_),
    .Y(_0029_)
  );
  NAND _1037_ (
    .A(_0415_),
    .B(_0486_),
    .Y(_0490_)
  );
  NAND _1038_ (
    .A(\ram[5] [8]),
    .B(_0487_),
    .Y(_0491_)
  );
  NAND _1039_ (
    .A(_0490_),
    .B(_0491_),
    .Y(_0028_)
  );
  NAND _1040_ (
    .A(_0418_),
    .B(_0486_),
    .Y(_0492_)
  );
  NAND _1041_ (
    .A(\ram[5] [7]),
    .B(_0487_),
    .Y(_0493_)
  );
  NAND _1042_ (
    .A(_0492_),
    .B(_0493_),
    .Y(_0027_)
  );
  NAND _1043_ (
    .A(_0421_),
    .B(_0486_),
    .Y(_0494_)
  );
  NAND _1044_ (
    .A(\ram[5] [6]),
    .B(_0487_),
    .Y(_0495_)
  );
  NAND _1045_ (
    .A(_0494_),
    .B(_0495_),
    .Y(_0026_)
  );
  NAND _1046_ (
    .A(_0424_),
    .B(_0486_),
    .Y(_0496_)
  );
  NAND _1047_ (
    .A(\ram[5] [5]),
    .B(_0487_),
    .Y(_0497_)
  );
  NAND _1048_ (
    .A(_0496_),
    .B(_0497_),
    .Y(_0025_)
  );
  NAND _1049_ (
    .A(_0427_),
    .B(_0486_),
    .Y(_0498_)
  );
  NAND _1050_ (
    .A(\ram[5] [4]),
    .B(_0487_),
    .Y(_0499_)
  );
  NAND _1051_ (
    .A(_0498_),
    .B(_0499_),
    .Y(_0024_)
  );
  NAND _1052_ (
    .A(_0430_),
    .B(_0486_),
    .Y(_0500_)
  );
  NAND _1053_ (
    .A(\ram[5] [3]),
    .B(_0487_),
    .Y(_0501_)
  );
  NAND _1054_ (
    .A(_0500_),
    .B(_0501_),
    .Y(_0023_)
  );
  NAND _1055_ (
    .A(_0433_),
    .B(_0486_),
    .Y(_0502_)
  );
  NAND _1056_ (
    .A(\ram[5] [2]),
    .B(_0487_),
    .Y(_0503_)
  );
  NAND _1057_ (
    .A(_0502_),
    .B(_0503_),
    .Y(_0022_)
  );
  NAND _1058_ (
    .A(_0436_),
    .B(_0486_),
    .Y(_0504_)
  );
  NAND _1059_ (
    .A(\ram[5] [1]),
    .B(_0487_),
    .Y(_0505_)
  );
  NAND _1060_ (
    .A(_0504_),
    .B(_0505_),
    .Y(_0021_)
  );
  NAND _1061_ (
    .A(_0439_),
    .B(_0486_),
    .Y(_0506_)
  );
  NAND _1062_ (
    .A(\ram[5] [0]),
    .B(_0487_),
    .Y(_0507_)
  );
  NAND _1063_ (
    .A(_0506_),
    .B(_0507_),
    .Y(_0020_)
  );
  NOR _1064_ (
    .A(_0144_),
    .B(_0359_),
    .Y(_0508_)
  );
  NAND _1065_ (
    .A(addr_wa[1]),
    .B(_0358_),
    .Y(_0509_)
  );
  NOR _1066_ (
    .A(addr_wa[0]),
    .B(_0509_),
    .Y(_0510_)
  );
  NAND _1067_ (
    .A(_0143_),
    .B(_0508_),
    .Y(_0511_)
  );
  NAND _1068_ (
    .A(_0412_),
    .B(_0510_),
    .Y(_0512_)
  );
  NAND _1069_ (
    .A(\ram[6] [9]),
    .B(_0511_),
    .Y(_0513_)
  );
  NAND _1070_ (
    .A(_0512_),
    .B(_0513_),
    .Y(_0019_)
  );
  NAND _1071_ (
    .A(_0415_),
    .B(_0510_),
    .Y(_0514_)
  );
  NAND _1072_ (
    .A(\ram[6] [8]),
    .B(_0511_),
    .Y(_0515_)
  );
  NAND _1073_ (
    .A(_0514_),
    .B(_0515_),
    .Y(_0018_)
  );
  NAND _1074_ (
    .A(_0418_),
    .B(_0510_),
    .Y(_0516_)
  );
  NAND _1075_ (
    .A(\ram[6] [7]),
    .B(_0511_),
    .Y(_0517_)
  );
  NAND _1076_ (
    .A(_0516_),
    .B(_0517_),
    .Y(_0017_)
  );
  NAND _1077_ (
    .A(_0421_),
    .B(_0510_),
    .Y(_0518_)
  );
  NAND _1078_ (
    .A(\ram[6] [6]),
    .B(_0511_),
    .Y(_0519_)
  );
  NAND _1079_ (
    .A(_0518_),
    .B(_0519_),
    .Y(_0016_)
  );
  NAND _1080_ (
    .A(_0424_),
    .B(_0510_),
    .Y(_0520_)
  );
  NAND _1081_ (
    .A(\ram[6] [5]),
    .B(_0511_),
    .Y(_0521_)
  );
  NAND _1082_ (
    .A(_0520_),
    .B(_0521_),
    .Y(_0015_)
  );
  NAND _1083_ (
    .A(_0427_),
    .B(_0510_),
    .Y(_0522_)
  );
  NAND _1084_ (
    .A(\ram[6] [4]),
    .B(_0511_),
    .Y(_0523_)
  );
  NAND _1085_ (
    .A(_0522_),
    .B(_0523_),
    .Y(_0014_)
  );
  NAND _1086_ (
    .A(_0430_),
    .B(_0510_),
    .Y(_0524_)
  );
  NAND _1087_ (
    .A(\ram[6] [3]),
    .B(_0511_),
    .Y(_0525_)
  );
  NAND _1088_ (
    .A(_0524_),
    .B(_0525_),
    .Y(_0013_)
  );
  NAND _1089_ (
    .A(_0433_),
    .B(_0510_),
    .Y(_0526_)
  );
  NAND _1090_ (
    .A(\ram[6] [2]),
    .B(_0511_),
    .Y(_0527_)
  );
  NAND _1091_ (
    .A(_0526_),
    .B(_0527_),
    .Y(_0012_)
  );
  NAND _1092_ (
    .A(_0436_),
    .B(_0510_),
    .Y(_0528_)
  );
  NAND _1093_ (
    .A(\ram[6] [1]),
    .B(_0511_),
    .Y(_0529_)
  );
  NAND _1094_ (
    .A(_0528_),
    .B(_0529_),
    .Y(_0011_)
  );
  NAND _1095_ (
    .A(_0439_),
    .B(_0510_),
    .Y(_0530_)
  );
  NAND _1096_ (
    .A(\ram[6] [0]),
    .B(_0511_),
    .Y(_0531_)
  );
  NAND _1097_ (
    .A(_0530_),
    .B(_0531_),
    .Y(_0010_)
  );
  NOR _1098_ (
    .A(_0143_),
    .B(_0509_),
    .Y(_0532_)
  );
  NAND _1099_ (
    .A(addr_wa[0]),
    .B(_0508_),
    .Y(_0533_)
  );
  NAND _1100_ (
    .A(_0412_),
    .B(_0532_),
    .Y(_0534_)
  );
  NAND _1101_ (
    .A(\ram[7] [9]),
    .B(_0533_),
    .Y(_0535_)
  );
  NAND _1102_ (
    .A(_0534_),
    .B(_0535_),
    .Y(_0009_)
  );
  NAND _1103_ (
    .A(_0415_),
    .B(_0532_),
    .Y(_0536_)
  );
  NAND _1104_ (
    .A(\ram[7] [8]),
    .B(_0533_),
    .Y(_0537_)
  );
  NAND _1105_ (
    .A(_0536_),
    .B(_0537_),
    .Y(_0008_)
  );
  NAND _1106_ (
    .A(_0418_),
    .B(_0532_),
    .Y(_0538_)
  );
  NAND _1107_ (
    .A(\ram[7] [7]),
    .B(_0533_),
    .Y(_0539_)
  );
  NAND _1108_ (
    .A(_0538_),
    .B(_0539_),
    .Y(_0007_)
  );
  NAND _1109_ (
    .A(_0421_),
    .B(_0532_),
    .Y(_0540_)
  );
  NAND _1110_ (
    .A(\ram[7] [6]),
    .B(_0533_),
    .Y(_0541_)
  );
  NAND _1111_ (
    .A(_0540_),
    .B(_0541_),
    .Y(_0006_)
  );
  NAND _1112_ (
    .A(_0424_),
    .B(_0532_),
    .Y(_0542_)
  );
  NAND _1113_ (
    .A(\ram[7] [5]),
    .B(_0533_),
    .Y(_0543_)
  );
  NAND _1114_ (
    .A(_0542_),
    .B(_0543_),
    .Y(_0005_)
  );
  NAND _1115_ (
    .A(_0427_),
    .B(_0532_),
    .Y(_0544_)
  );
  NAND _1116_ (
    .A(\ram[7] [4]),
    .B(_0533_),
    .Y(_0545_)
  );
  NAND _1117_ (
    .A(_0544_),
    .B(_0545_),
    .Y(_0004_)
  );
  NAND _1118_ (
    .A(_0430_),
    .B(_0532_),
    .Y(_0546_)
  );
  NAND _1119_ (
    .A(\ram[7] [3]),
    .B(_0533_),
    .Y(_0547_)
  );
  NAND _1120_ (
    .A(_0546_),
    .B(_0547_),
    .Y(_0003_)
  );
  NAND _1121_ (
    .A(_0433_),
    .B(_0532_),
    .Y(_0548_)
  );
  NAND _1122_ (
    .A(\ram[7] [2]),
    .B(_0533_),
    .Y(_0549_)
  );
  NAND _1123_ (
    .A(_0548_),
    .B(_0549_),
    .Y(_0002_)
  );
  NAND _1124_ (
    .A(_0436_),
    .B(_0532_),
    .Y(_0550_)
  );
  NAND _1125_ (
    .A(\ram[7] [1]),
    .B(_0533_),
    .Y(_0551_)
  );
  NAND _1126_ (
    .A(_0550_),
    .B(_0551_),
    .Y(_0001_)
  );
  NAND _1127_ (
    .A(_0439_),
    .B(_0532_),
    .Y(_0552_)
  );
  NAND _1128_ (
    .A(\ram[7] [0]),
    .B(_0533_),
    .Y(_0553_)
  );
  NAND _1129_ (
    .A(_0552_),
    .B(_0553_),
    .Y(_0000_)
  );
  NAND _1130_ (
    .A(_0120_),
    .B(addr_ra[2]),
    .Y(_0554_)
  );
  NOR _1131_ (
    .A(\ram[3] [9]),
    .B(addr_ra[2]),
    .Y(_0555_)
  );
  NAND _1132_ (
    .A(addr_ra[0]),
    .B(_0554_),
    .Y(_0556_)
  );
  NOR _1133_ (
    .A(_0555_),
    .B(_0556_),
    .Y(_0557_)
  );
  NOR _1134_ (
    .A(\ram[2] [9]),
    .B(addr_ra[2]),
    .Y(_0558_)
  );
  NOT _1135_ (
    .A(_0558_),
    .Y(_0559_)
  );
  NAND _1136_ (
    .A(_0110_),
    .B(addr_ra[2]),
    .Y(_0560_)
  );
  NAND _1137_ (
    .A(_0559_),
    .B(_0560_),
    .Y(_0561_)
  );
  NOR _1138_ (
    .A(addr_ra[0]),
    .B(_0561_),
    .Y(_0562_)
  );
  NOR _1139_ (
    .A(_0557_),
    .B(_0562_),
    .Y(_0563_)
  );
  NOR _1140_ (
    .A(_0131_),
    .B(_0563_),
    .Y(_0564_)
  );
  NAND _1141_ (
    .A(_0100_),
    .B(addr_ra[2]),
    .Y(_0565_)
  );
  NOR _1142_ (
    .A(\ram[1] [9]),
    .B(addr_ra[2]),
    .Y(_0566_)
  );
  NAND _1143_ (
    .A(addr_ra[0]),
    .B(_0565_),
    .Y(_0567_)
  );
  NOR _1144_ (
    .A(_0566_),
    .B(_0567_),
    .Y(_0568_)
  );
  NOR _1145_ (
    .A(\ram[0] [9]),
    .B(addr_ra[2]),
    .Y(_0569_)
  );
  NOT _1146_ (
    .A(_0569_),
    .Y(_0570_)
  );
  NAND _1147_ (
    .A(_0090_),
    .B(addr_ra[2]),
    .Y(_0571_)
  );
  NAND _1148_ (
    .A(_0570_),
    .B(_0571_),
    .Y(_0572_)
  );
  NOR _1149_ (
    .A(addr_ra[0]),
    .B(_0572_),
    .Y(_0573_)
  );
  NOR _1150_ (
    .A(_0568_),
    .B(_0573_),
    .Y(_0574_)
  );
  NOR _1151_ (
    .A(addr_ra[1]),
    .B(_0574_),
    .Y(_0575_)
  );
  NOR _1152_ (
    .A(_0564_),
    .B(_0575_),
    .Y(_0576_)
  );
  NOR _1153_ (
    .A(_0146_),
    .B(_0576_),
    .Y(_0089_)
  );
  DFF _1154_ (
    .C(clk),
    .D(_0000_),
    .Q(\ram[7] [0])
  );
  DFF _1155_ (
    .C(clk),
    .D(_0001_),
    .Q(\ram[7] [1])
  );
  DFF _1156_ (
    .C(clk),
    .D(_0002_),
    .Q(\ram[7] [2])
  );
  DFF _1157_ (
    .C(clk),
    .D(_0003_),
    .Q(\ram[7] [3])
  );
  DFF _1158_ (
    .C(clk),
    .D(_0004_),
    .Q(\ram[7] [4])
  );
  DFF _1159_ (
    .C(clk),
    .D(_0005_),
    .Q(\ram[7] [5])
  );
  DFF _1160_ (
    .C(clk),
    .D(_0006_),
    .Q(\ram[7] [6])
  );
  DFF _1161_ (
    .C(clk),
    .D(_0007_),
    .Q(\ram[7] [7])
  );
  DFF _1162_ (
    .C(clk),
    .D(_0008_),
    .Q(\ram[7] [8])
  );
  DFF _1163_ (
    .C(clk),
    .D(_0009_),
    .Q(\ram[7] [9])
  );
  DFF _1164_ (
    .C(clk),
    .D(_0010_),
    .Q(\ram[6] [0])
  );
  DFF _1165_ (
    .C(clk),
    .D(_0011_),
    .Q(\ram[6] [1])
  );
  DFF _1166_ (
    .C(clk),
    .D(_0012_),
    .Q(\ram[6] [2])
  );
  DFF _1167_ (
    .C(clk),
    .D(_0013_),
    .Q(\ram[6] [3])
  );
  DFF _1168_ (
    .C(clk),
    .D(_0014_),
    .Q(\ram[6] [4])
  );
  DFF _1169_ (
    .C(clk),
    .D(_0015_),
    .Q(\ram[6] [5])
  );
  DFF _1170_ (
    .C(clk),
    .D(_0016_),
    .Q(\ram[6] [6])
  );
  DFF _1171_ (
    .C(clk),
    .D(_0017_),
    .Q(\ram[6] [7])
  );
  DFF _1172_ (
    .C(clk),
    .D(_0018_),
    .Q(\ram[6] [8])
  );
  DFF _1173_ (
    .C(clk),
    .D(_0019_),
    .Q(\ram[6] [9])
  );
  DFF _1174_ (
    .C(clk),
    .D(_0020_),
    .Q(\ram[5] [0])
  );
  DFF _1175_ (
    .C(clk),
    .D(_0021_),
    .Q(\ram[5] [1])
  );
  DFF _1176_ (
    .C(clk),
    .D(_0022_),
    .Q(\ram[5] [2])
  );
  DFF _1177_ (
    .C(clk),
    .D(_0023_),
    .Q(\ram[5] [3])
  );
  DFF _1178_ (
    .C(clk),
    .D(_0024_),
    .Q(\ram[5] [4])
  );
  DFF _1179_ (
    .C(clk),
    .D(_0025_),
    .Q(\ram[5] [5])
  );
  DFF _1180_ (
    .C(clk),
    .D(_0026_),
    .Q(\ram[5] [6])
  );
  DFF _1181_ (
    .C(clk),
    .D(_0027_),
    .Q(\ram[5] [7])
  );
  DFF _1182_ (
    .C(clk),
    .D(_0028_),
    .Q(\ram[5] [8])
  );
  DFF _1183_ (
    .C(clk),
    .D(_0029_),
    .Q(\ram[5] [9])
  );
  DFF _1184_ (
    .C(clk),
    .D(_0030_),
    .Q(\ram[4] [0])
  );
  DFF _1185_ (
    .C(clk),
    .D(_0031_),
    .Q(\ram[4] [1])
  );
  DFF _1186_ (
    .C(clk),
    .D(_0032_),
    .Q(\ram[4] [2])
  );
  DFF _1187_ (
    .C(clk),
    .D(_0033_),
    .Q(\ram[4] [3])
  );
  DFF _1188_ (
    .C(clk),
    .D(_0034_),
    .Q(\ram[4] [4])
  );
  DFF _1189_ (
    .C(clk),
    .D(_0035_),
    .Q(\ram[4] [5])
  );
  DFF _1190_ (
    .C(clk),
    .D(_0036_),
    .Q(\ram[4] [6])
  );
  DFF _1191_ (
    .C(clk),
    .D(_0037_),
    .Q(\ram[4] [7])
  );
  DFF _1192_ (
    .C(clk),
    .D(_0038_),
    .Q(\ram[4] [8])
  );
  DFF _1193_ (
    .C(clk),
    .D(_0039_),
    .Q(\ram[4] [9])
  );
  DFF _1194_ (
    .C(clk),
    .D(_0040_),
    .Q(\ram[3] [0])
  );
  DFF _1195_ (
    .C(clk),
    .D(_0041_),
    .Q(\ram[3] [1])
  );
  DFF _1196_ (
    .C(clk),
    .D(_0042_),
    .Q(\ram[3] [2])
  );
  DFF _1197_ (
    .C(clk),
    .D(_0043_),
    .Q(\ram[3] [3])
  );
  DFF _1198_ (
    .C(clk),
    .D(_0044_),
    .Q(\ram[3] [4])
  );
  DFF _1199_ (
    .C(clk),
    .D(_0045_),
    .Q(\ram[3] [5])
  );
  DFF _1200_ (
    .C(clk),
    .D(_0046_),
    .Q(\ram[3] [6])
  );
  DFF _1201_ (
    .C(clk),
    .D(_0047_),
    .Q(\ram[3] [7])
  );
  DFF _1202_ (
    .C(clk),
    .D(_0048_),
    .Q(\ram[3] [8])
  );
  DFF _1203_ (
    .C(clk),
    .D(_0049_),
    .Q(\ram[3] [9])
  );
  DFF _1204_ (
    .C(clk),
    .D(_0050_),
    .Q(\ram[2] [0])
  );
  DFF _1205_ (
    .C(clk),
    .D(_0051_),
    .Q(\ram[2] [1])
  );
  DFF _1206_ (
    .C(clk),
    .D(_0052_),
    .Q(\ram[2] [2])
  );
  DFF _1207_ (
    .C(clk),
    .D(_0053_),
    .Q(\ram[2] [3])
  );
  DFF _1208_ (
    .C(clk),
    .D(_0054_),
    .Q(\ram[2] [4])
  );
  DFF _1209_ (
    .C(clk),
    .D(_0055_),
    .Q(\ram[2] [5])
  );
  DFF _1210_ (
    .C(clk),
    .D(_0056_),
    .Q(\ram[2] [6])
  );
  DFF _1211_ (
    .C(clk),
    .D(_0057_),
    .Q(\ram[2] [7])
  );
  DFF _1212_ (
    .C(clk),
    .D(_0058_),
    .Q(\ram[2] [8])
  );
  DFF _1213_ (
    .C(clk),
    .D(_0059_),
    .Q(\ram[2] [9])
  );
  DFF _1214_ (
    .C(clk),
    .D(_0060_),
    .Q(\ram[1] [0])
  );
  DFF _1215_ (
    .C(clk),
    .D(_0061_),
    .Q(\ram[1] [1])
  );
  DFF _1216_ (
    .C(clk),
    .D(_0062_),
    .Q(\ram[1] [2])
  );
  DFF _1217_ (
    .C(clk),
    .D(_0063_),
    .Q(\ram[1] [3])
  );
  DFF _1218_ (
    .C(clk),
    .D(_0064_),
    .Q(\ram[1] [4])
  );
  DFF _1219_ (
    .C(clk),
    .D(_0065_),
    .Q(\ram[1] [5])
  );
  DFF _1220_ (
    .C(clk),
    .D(_0066_),
    .Q(\ram[1] [6])
  );
  DFF _1221_ (
    .C(clk),
    .D(_0067_),
    .Q(\ram[1] [7])
  );
  DFF _1222_ (
    .C(clk),
    .D(_0068_),
    .Q(\ram[1] [8])
  );
  DFF _1223_ (
    .C(clk),
    .D(_0069_),
    .Q(\ram[1] [9])
  );
  DFF _1224_ (
    .C(clk),
    .D(_0070_),
    .Q(\ram[0] [0])
  );
  DFF _1225_ (
    .C(clk),
    .D(_0071_),
    .Q(\ram[0] [1])
  );
  DFF _1226_ (
    .C(clk),
    .D(_0072_),
    .Q(\ram[0] [2])
  );
  DFF _1227_ (
    .C(clk),
    .D(_0073_),
    .Q(\ram[0] [3])
  );
  DFF _1228_ (
    .C(clk),
    .D(_0074_),
    .Q(\ram[0] [4])
  );
  DFF _1229_ (
    .C(clk),
    .D(_0075_),
    .Q(\ram[0] [5])
  );
  DFF _1230_ (
    .C(clk),
    .D(_0076_),
    .Q(\ram[0] [6])
  );
  DFF _1231_ (
    .C(clk),
    .D(_0077_),
    .Q(\ram[0] [7])
  );
  DFF _1232_ (
    .C(clk),
    .D(_0078_),
    .Q(\ram[0] [8])
  );
  DFF _1233_ (
    .C(clk),
    .D(_0079_),
    .Q(\ram[0] [9])
  );
  (* src = "true_dpram_sclk_estruct.v:31.2-50.5" *)
  DFF _1234_ (
    .C(clk),
    .D(_0080_),
    .Q(q_a[0])
  );
  (* src = "true_dpram_sclk_estruct.v:31.2-50.5" *)
  DFF _1235_ (
    .C(clk),
    .D(_0081_),
    .Q(q_a[1])
  );
  (* src = "true_dpram_sclk_estruct.v:31.2-50.5" *)
  DFF _1236_ (
    .C(clk),
    .D(_0082_),
    .Q(q_a[2])
  );
  (* src = "true_dpram_sclk_estruct.v:31.2-50.5" *)
  DFF _1237_ (
    .C(clk),
    .D(_0083_),
    .Q(q_a[3])
  );
  (* src = "true_dpram_sclk_estruct.v:31.2-50.5" *)
  DFF _1238_ (
    .C(clk),
    .D(_0084_),
    .Q(q_a[4])
  );
  (* src = "true_dpram_sclk_estruct.v:31.2-50.5" *)
  DFF _1239_ (
    .C(clk),
    .D(_0085_),
    .Q(q_a[5])
  );
  (* src = "true_dpram_sclk_estruct.v:31.2-50.5" *)
  DFF _1240_ (
    .C(clk),
    .D(_0086_),
    .Q(q_a[6])
  );
  (* src = "true_dpram_sclk_estruct.v:31.2-50.5" *)
  DFF _1241_ (
    .C(clk),
    .D(_0087_),
    .Q(q_a[7])
  );
  (* src = "true_dpram_sclk_estruct.v:31.2-50.5" *)
  DFF _1242_ (
    .C(clk),
    .D(_0088_),
    .Q(q_a[8])
  );
  (* src = "true_dpram_sclk_estruct.v:31.2-50.5" *)
  DFF _1243_ (
    .C(clk),
    .D(_0089_),
    .Q(q_a[9])
  );
endmodule
