/* Generated by Yosys 0.9+4052 (git sha1 44520808, gcc 9.3.0-17ubuntu1~20.04 -fPIC -Os) */

(* top =  1  *)
(* src = "MaquinaEstados_estruct.v:1.1-81.10" *)
module MaquinaEstados_estruct(clk, Umbral_alto, Umbral_bajo, reset, init, empties, umbral_superior, umbral_inferior, state);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  (* src = "MaquinaEstados_estruct.v:10.26-10.32" *)
  wire [3:0] Estado;
  (* src = "MaquinaEstados_estruct.v:3.17-3.28" *)
  input [2:0] Umbral_alto;
  (* src = "MaquinaEstados_estruct.v:3.30-3.41" *)
  input [2:0] Umbral_bajo;
  (* src = "MaquinaEstados_estruct.v:2.11-2.14" *)
  input clk;
  (* src = "MaquinaEstados_estruct.v:6.17-6.24" *)
  input [7:0] empties;
  (* src = "MaquinaEstados_estruct.v:5.11-5.15" *)
  input init;
  (* src = "MaquinaEstados_estruct.v:4.11-4.16" *)
  input reset;
  (* src = "MaquinaEstados_estruct.v:8.22-8.27" *)
  output [3:0] state;
  (* src = "MaquinaEstados_estruct.v:7.39-7.54" *)
  output [2:0] umbral_inferior;
  (* src = "MaquinaEstados_estruct.v:7.22-7.37" *)
  output [2:0] umbral_superior;
  NOT _078_ (
    .A(umbral_inferior[2]),
    .Y(_026_)
  );
  NOT _079_ (
    .A(init),
    .Y(_027_)
  );
  NOT _080_ (
    .A(Umbral_bajo[1]),
    .Y(_028_)
  );
  NOT _081_ (
    .A(umbral_inferior[0]),
    .Y(_029_)
  );
  NOT _082_ (
    .A(umbral_superior[2]),
    .Y(_030_)
  );
  NOT _083_ (
    .A(umbral_superior[1]),
    .Y(_031_)
  );
  NOT _084_ (
    .A(umbral_superior[0]),
    .Y(_032_)
  );
  NOT _085_ (
    .A(Estado[1]),
    .Y(_033_)
  );
  NOT _086_ (
    .A(Estado[2]),
    .Y(_034_)
  );
  NOT _087_ (
    .A(Estado[3]),
    .Y(_035_)
  );
  NOR _088_ (
    .A(init),
    .B(umbral_inferior[1]),
    .Y(_036_)
  );
  NOR _089_ (
    .A(init),
    .B(reset),
    .Y(_037_)
  );
  NOT _090_ (
    .A(_037_),
    .Y(_038_)
  );
  NOR _091_ (
    .A(reset),
    .B(_028_),
    .Y(_039_)
  );
  NOR _092_ (
    .A(_037_),
    .B(_039_),
    .Y(_040_)
  );
  NOR _093_ (
    .A(_036_),
    .B(_040_),
    .Y(_008_)
  );
  NAND _094_ (
    .A(init),
    .B(Umbral_bajo[0]),
    .Y(_041_)
  );
  NOT _095_ (
    .A(_041_),
    .Y(_042_)
  );
  NOR _096_ (
    .A(init),
    .B(_029_),
    .Y(_043_)
  );
  NOR _097_ (
    .A(_042_),
    .B(_043_),
    .Y(_044_)
  );
  NOR _098_ (
    .A(reset),
    .B(_044_),
    .Y(_007_)
  );
  NAND _099_ (
    .A(init),
    .B(Umbral_alto[2]),
    .Y(_045_)
  );
  NOT _100_ (
    .A(_045_),
    .Y(_046_)
  );
  NOR _101_ (
    .A(init),
    .B(_030_),
    .Y(_047_)
  );
  NOR _102_ (
    .A(_046_),
    .B(_047_),
    .Y(_048_)
  );
  NOR _103_ (
    .A(reset),
    .B(_048_),
    .Y(_006_)
  );
  NAND _104_ (
    .A(init),
    .B(Umbral_alto[1]),
    .Y(_049_)
  );
  NOT _105_ (
    .A(_049_),
    .Y(_050_)
  );
  NOR _106_ (
    .A(init),
    .B(_031_),
    .Y(_051_)
  );
  NOR _107_ (
    .A(_050_),
    .B(_051_),
    .Y(_052_)
  );
  NOR _108_ (
    .A(reset),
    .B(_052_),
    .Y(_005_)
  );
  NAND _109_ (
    .A(init),
    .B(Umbral_alto[0]),
    .Y(_053_)
  );
  NOT _110_ (
    .A(_053_),
    .Y(_054_)
  );
  NOR _111_ (
    .A(init),
    .B(_032_),
    .Y(_055_)
  );
  NOR _112_ (
    .A(_054_),
    .B(_055_),
    .Y(_056_)
  );
  NOR _113_ (
    .A(reset),
    .B(_056_),
    .Y(_004_)
  );
  NOR _114_ (
    .A(Estado[2]),
    .B(Estado[3]),
    .Y(_057_)
  );
  NAND _115_ (
    .A(_034_),
    .B(_035_),
    .Y(_058_)
  );
  NOR _116_ (
    .A(Estado[0]),
    .B(_058_),
    .Y(_059_)
  );
  NOR _117_ (
    .A(_033_),
    .B(_057_),
    .Y(_060_)
  );
  NAND _118_ (
    .A(Estado[0]),
    .B(_057_),
    .Y(_061_)
  );
  NAND _119_ (
    .A(_027_),
    .B(_061_),
    .Y(_062_)
  );
  NOR _120_ (
    .A(_060_),
    .B(_062_),
    .Y(_063_)
  );
  NOR _121_ (
    .A(reset),
    .B(_063_),
    .Y(_003_)
  );
  NAND _122_ (
    .A(_027_),
    .B(Estado[0]),
    .Y(_064_)
  );
  NOR _123_ (
    .A(Estado[1]),
    .B(_058_),
    .Y(_065_)
  );
  NAND _124_ (
    .A(Estado[1]),
    .B(_059_),
    .Y(_066_)
  );
  NOR _125_ (
    .A(_064_),
    .B(_065_),
    .Y(_067_)
  );
  NOR _126_ (
    .A(reset),
    .B(_067_),
    .Y(_068_)
  );
  NOT _127_ (
    .A(_068_),
    .Y(_002_)
  );
  NAND _128_ (
    .A(Estado[2]),
    .B(Estado[3]),
    .Y(_069_)
  );
  NOR _129_ (
    .A(Estado[1]),
    .B(Estado[0]),
    .Y(_070_)
  );
  NAND _130_ (
    .A(_069_),
    .B(_070_),
    .Y(_071_)
  );
  NOR _131_ (
    .A(_057_),
    .B(_071_),
    .Y(_072_)
  );
  NOT _132_ (
    .A(_072_),
    .Y(_073_)
  );
  NAND _133_ (
    .A(empties[4]),
    .B(empties[5]),
    .Y(_074_)
  );
  NAND _134_ (
    .A(empties[6]),
    .B(empties[7]),
    .Y(_075_)
  );
  NOR _135_ (
    .A(_074_),
    .B(_075_),
    .Y(_076_)
  );
  NAND _136_ (
    .A(empties[0]),
    .B(empties[1]),
    .Y(_077_)
  );
  NAND _137_ (
    .A(empties[2]),
    .B(empties[3]),
    .Y(_010_)
  );
  NOR _138_ (
    .A(_077_),
    .B(_010_),
    .Y(_011_)
  );
  NAND _139_ (
    .A(_076_),
    .B(_011_),
    .Y(_012_)
  );
  NOT _140_ (
    .A(_012_),
    .Y(_013_)
  );
  NOR _141_ (
    .A(_073_),
    .B(_012_),
    .Y(_014_)
  );
  NAND _142_ (
    .A(_072_),
    .B(_013_),
    .Y(_015_)
  );
  NAND _143_ (
    .A(Estado[2]),
    .B(_071_),
    .Y(_016_)
  );
  NAND _144_ (
    .A(_066_),
    .B(_016_),
    .Y(_017_)
  );
  NOR _145_ (
    .A(_014_),
    .B(_017_),
    .Y(_018_)
  );
  NOR _146_ (
    .A(_038_),
    .B(_018_),
    .Y(_001_)
  );
  NAND _147_ (
    .A(_035_),
    .B(_073_),
    .Y(_019_)
  );
  NAND _148_ (
    .A(_015_),
    .B(_019_),
    .Y(_020_)
  );
  NOR _149_ (
    .A(_038_),
    .B(_020_),
    .Y(_000_)
  );
  NAND _150_ (
    .A(Umbral_bajo[2]),
    .B(init),
    .Y(_021_)
  );
  NOT _151_ (
    .A(_021_),
    .Y(_022_)
  );
  NOR _152_ (
    .A(_026_),
    .B(init),
    .Y(_023_)
  );
  NOR _153_ (
    .A(_022_),
    .B(_023_),
    .Y(_024_)
  );
  NOR _154_ (
    .A(reset),
    .B(_024_),
    .Y(_009_)
  );
  NOR _155_ (
    .A(reset),
    .B(Estado[0]),
    .Y(_025_)
  );
  NOT _156_ (
    .A(_025_),
    .Y(state[0])
  );
  NOR _157_ (
    .A(reset),
    .B(_033_),
    .Y(state[1])
  );
  NOR _158_ (
    .A(reset),
    .B(_034_),
    .Y(state[2])
  );
  NOR _159_ (
    .A(reset),
    .B(_035_),
    .Y(state[3])
  );
  (* src = "MaquinaEstados_estruct.v:17.1-33.4" *)
  DFF _160_ (
    .C(clk),
    .D(_000_),
    .Q(Estado[3])
  );
  (* src = "MaquinaEstados_estruct.v:17.1-33.4" *)
  DFF _161_ (
    .C(clk),
    .D(_001_),
    .Q(Estado[2])
  );
  (* src = "MaquinaEstados_estruct.v:17.1-33.4" *)
  DFF _162_ (
    .C(clk),
    .D(_002_),
    .Q(Estado[0])
  );
  (* src = "MaquinaEstados_estruct.v:17.1-33.4" *)
  DFF _163_ (
    .C(clk),
    .D(_003_),
    .Q(Estado[1])
  );
  (* src = "MaquinaEstados_estruct.v:17.1-33.4" *)
  DFF _164_ (
    .C(clk),
    .D(_004_),
    .Q(umbral_superior[0])
  );
  (* src = "MaquinaEstados_estruct.v:17.1-33.4" *)
  DFF _165_ (
    .C(clk),
    .D(_005_),
    .Q(umbral_superior[1])
  );
  (* src = "MaquinaEstados_estruct.v:17.1-33.4" *)
  DFF _166_ (
    .C(clk),
    .D(_006_),
    .Q(umbral_superior[2])
  );
  (* src = "MaquinaEstados_estruct.v:17.1-33.4" *)
  DFF _167_ (
    .C(clk),
    .D(_007_),
    .Q(umbral_inferior[0])
  );
  (* src = "MaquinaEstados_estruct.v:17.1-33.4" *)
  DFF _168_ (
    .C(clk),
    .D(_008_),
    .Q(umbral_inferior[1])
  );
  (* src = "MaquinaEstados_estruct.v:17.1-33.4" *)
  DFF _169_ (
    .C(clk),
    .D(_009_),
    .Q(umbral_inferior[2])
  );
endmodule
