/* Generated by Yosys 0.9+4052 (git sha1 44520808, gcc 9.3.0-17ubuntu1~20.04 -fPIC -Os) */

(* top =  1  *)
(* src = "MaquinaEstados.v:1.1-89.10" *)
module MaquinaEstados(clk, Umbral_alto, Umbral_bajo, reset, init, Empties, Umbral_superior, Umbral_inferior, state);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  (* src = "MaquinaEstados.v:6.17-6.24" *)
  input [7:0] Empties;
  (* src = "MaquinaEstados.v:10.26-10.32" *)
  wire [3:0] Estado;
  (* src = "MaquinaEstados.v:3.17-3.28" *)
  input [2:0] Umbral_alto;
  (* src = "MaquinaEstados.v:3.30-3.41" *)
  input [2:0] Umbral_bajo;
  (* src = "MaquinaEstados.v:7.39-7.54" *)
  output [2:0] Umbral_inferior;
  (* src = "MaquinaEstados.v:7.22-7.37" *)
  output [2:0] Umbral_superior;
  (* src = "MaquinaEstados.v:2.11-2.14" *)
  input clk;
  (* src = "MaquinaEstados.v:5.11-5.15" *)
  input init;
  (* src = "MaquinaEstados.v:4.11-4.16" *)
  input reset;
  (* src = "MaquinaEstados.v:8.22-8.27" *)
  output [3:0] state;
  NOT _070_ (
    .A(Estado[1]),
    .Y(_018_)
  );
  NOT _071_ (
    .A(reset),
    .Y(_019_)
  );
  NOT _072_ (
    .A(Estado[0]),
    .Y(_020_)
  );
  NOT _073_ (
    .A(Umbral_alto[2]),
    .Y(_021_)
  );
  NOT _074_ (
    .A(Umbral_alto[1]),
    .Y(_022_)
  );
  NOT _075_ (
    .A(Umbral_alto[0]),
    .Y(_023_)
  );
  NOT _076_ (
    .A(Umbral_bajo[2]),
    .Y(_024_)
  );
  NOT _077_ (
    .A(Umbral_bajo[1]),
    .Y(_025_)
  );
  NOT _078_ (
    .A(Umbral_bajo[0]),
    .Y(_026_)
  );
  NOT _079_ (
    .A(Estado[2]),
    .Y(_027_)
  );
  NOT _080_ (
    .A(Estado[3]),
    .Y(_028_)
  );
  NOR _081_ (
    .A(Estado[2]),
    .B(Estado[3]),
    .Y(_029_)
  );
  NAND _082_ (
    .A(Estado[0]),
    .B(_029_),
    .Y(_030_)
  );
  NOR _083_ (
    .A(Estado[1]),
    .B(_030_),
    .Y(_031_)
  );
  NOR _084_ (
    .A(init),
    .B(_031_),
    .Y(_032_)
  );
  NAND _085_ (
    .A(Estado[0]),
    .B(_032_),
    .Y(_033_)
  );
  NAND _086_ (
    .A(_019_),
    .B(_033_),
    .Y(_008_)
  );
  NOR _087_ (
    .A(_018_),
    .B(Estado[0]),
    .Y(_034_)
  );
  NAND _088_ (
    .A(_029_),
    .B(_034_),
    .Y(_035_)
  );
  NOR _089_ (
    .A(init),
    .B(_035_),
    .Y(_036_)
  );
  NOR _090_ (
    .A(Umbral_superior[2]),
    .B(_036_),
    .Y(_037_)
  );
  NAND _091_ (
    .A(_021_),
    .B(_036_),
    .Y(_038_)
  );
  NAND _092_ (
    .A(_019_),
    .B(_038_),
    .Y(_039_)
  );
  NOR _093_ (
    .A(_037_),
    .B(_039_),
    .Y(_007_)
  );
  NOR _094_ (
    .A(Umbral_superior[1]),
    .B(_036_),
    .Y(_040_)
  );
  NAND _095_ (
    .A(_022_),
    .B(_036_),
    .Y(_041_)
  );
  NAND _096_ (
    .A(_019_),
    .B(_041_),
    .Y(_042_)
  );
  NOR _097_ (
    .A(_040_),
    .B(_042_),
    .Y(_006_)
  );
  NOR _098_ (
    .A(Umbral_superior[0]),
    .B(_036_),
    .Y(_043_)
  );
  NAND _099_ (
    .A(_023_),
    .B(_036_),
    .Y(_044_)
  );
  NAND _100_ (
    .A(_019_),
    .B(_044_),
    .Y(_045_)
  );
  NOR _101_ (
    .A(_043_),
    .B(_045_),
    .Y(_005_)
  );
  NOR _102_ (
    .A(Umbral_inferior[2]),
    .B(_036_),
    .Y(_046_)
  );
  NAND _103_ (
    .A(_024_),
    .B(_036_),
    .Y(_047_)
  );
  NAND _104_ (
    .A(_019_),
    .B(_047_),
    .Y(_048_)
  );
  NOR _105_ (
    .A(_046_),
    .B(_048_),
    .Y(_004_)
  );
  NOR _106_ (
    .A(Umbral_inferior[1]),
    .B(_036_),
    .Y(_049_)
  );
  NAND _107_ (
    .A(_025_),
    .B(_036_),
    .Y(_050_)
  );
  NAND _108_ (
    .A(_019_),
    .B(_050_),
    .Y(_051_)
  );
  NOR _109_ (
    .A(_049_),
    .B(_051_),
    .Y(_003_)
  );
  NOR _110_ (
    .A(Umbral_inferior[0]),
    .B(_036_),
    .Y(_052_)
  );
  NAND _111_ (
    .A(_026_),
    .B(_036_),
    .Y(_053_)
  );
  NAND _112_ (
    .A(_019_),
    .B(_053_),
    .Y(_054_)
  );
  NOR _113_ (
    .A(_052_),
    .B(_054_),
    .Y(_002_)
  );
  NOR _114_ (
    .A(reset),
    .B(init),
    .Y(_055_)
  );
  NOT _115_ (
    .A(_055_),
    .Y(_056_)
  );
  NAND _116_ (
    .A(Estado[2]),
    .B(Estado[3]),
    .Y(_057_)
  );
  NOR _117_ (
    .A(Estado[1]),
    .B(Estado[0]),
    .Y(_058_)
  );
  NAND _118_ (
    .A(_057_),
    .B(_058_),
    .Y(_059_)
  );
  NOR _119_ (
    .A(_029_),
    .B(_059_),
    .Y(_060_)
  );
  NOR _120_ (
    .A(Empties[4]),
    .B(Empties[5]),
    .Y(_061_)
  );
  NOR _121_ (
    .A(Empties[6]),
    .B(Empties[7]),
    .Y(_062_)
  );
  NAND _122_ (
    .A(_061_),
    .B(_062_),
    .Y(_063_)
  );
  NOR _123_ (
    .A(Empties[0]),
    .B(Empties[1]),
    .Y(_064_)
  );
  NOR _124_ (
    .A(Empties[2]),
    .B(Empties[3]),
    .Y(_065_)
  );
  NAND _125_ (
    .A(_064_),
    .B(_065_),
    .Y(_066_)
  );
  NOR _126_ (
    .A(_063_),
    .B(_066_),
    .Y(_067_)
  );
  NAND _127_ (
    .A(_060_),
    .B(_067_),
    .Y(_068_)
  );
  NOT _128_ (
    .A(_068_),
    .Y(_069_)
  );
  NAND _129_ (
    .A(Estado[2]),
    .B(_059_),
    .Y(_010_)
  );
  NAND _130_ (
    .A(_035_),
    .B(_010_),
    .Y(_011_)
  );
  NOR _131_ (
    .A(_069_),
    .B(_011_),
    .Y(_012_)
  );
  NOR _132_ (
    .A(_056_),
    .B(_012_),
    .Y(_001_)
  );
  NOR _133_ (
    .A(Estado[3]),
    .B(_060_),
    .Y(_013_)
  );
  NAND _134_ (
    .A(_055_),
    .B(_068_),
    .Y(_014_)
  );
  NOR _135_ (
    .A(_013_),
    .B(_014_),
    .Y(_000_)
  );
  NAND _136_ (
    .A(Estado[1]),
    .B(_035_),
    .Y(_015_)
  );
  NAND _137_ (
    .A(_032_),
    .B(_015_),
    .Y(_016_)
  );
  NOT _138_ (
    .A(_016_),
    .Y(_017_)
  );
  NOR _139_ (
    .A(_018_),
    .B(reset),
    .Y(state[1])
  );
  NOR _140_ (
    .A(reset),
    .B(_017_),
    .Y(_009_)
  );
  NOR _141_ (
    .A(reset),
    .B(_020_),
    .Y(state[0])
  );
  NOR _142_ (
    .A(reset),
    .B(_027_),
    .Y(state[2])
  );
  NOR _143_ (
    .A(reset),
    .B(_028_),
    .Y(state[3])
  );
  (* src = "MaquinaEstados.v:17.1-37.4" *)
  DFF _144_ (
    .C(clk),
    .D(_000_),
    .Q(Estado[3])
  );
  (* src = "MaquinaEstados.v:17.1-37.4" *)
  DFF _145_ (
    .C(clk),
    .D(_001_),
    .Q(Estado[2])
  );
  (* src = "MaquinaEstados.v:17.1-37.4" *)
  DFF _146_ (
    .C(clk),
    .D(_002_),
    .Q(Umbral_inferior[0])
  );
  (* src = "MaquinaEstados.v:17.1-37.4" *)
  DFF _147_ (
    .C(clk),
    .D(_003_),
    .Q(Umbral_inferior[1])
  );
  (* src = "MaquinaEstados.v:17.1-37.4" *)
  DFF _148_ (
    .C(clk),
    .D(_004_),
    .Q(Umbral_inferior[2])
  );
  (* src = "MaquinaEstados.v:17.1-37.4" *)
  DFF _149_ (
    .C(clk),
    .D(_005_),
    .Q(Umbral_superior[0])
  );
  (* src = "MaquinaEstados.v:17.1-37.4" *)
  DFF _150_ (
    .C(clk),
    .D(_006_),
    .Q(Umbral_superior[1])
  );
  (* src = "MaquinaEstados.v:17.1-37.4" *)
  DFF _151_ (
    .C(clk),
    .D(_007_),
    .Q(Umbral_superior[2])
  );
  (* src = "MaquinaEstados.v:17.1-37.4" *)
  DFF _152_ (
    .C(clk),
    .D(_008_),
    .Q(Estado[0])
  );
  (* src = "MaquinaEstados.v:17.1-37.4" *)
  DFF _153_ (
    .C(clk),
    .D(_009_),
    .Q(Estado[1])
  );
endmodule
